--MEDICAMENTO (PK)
--USUARIA(PK)
--MEDICAMENTO-USUARIA(PK (FK_MEDICAMENTO, FK_USUARIA ))


--CICLOMENSTRUAL(PK, FK_USUARIA)
--EMBARAZO(PK, FK_USUARIA)

--REVISIONMEDICA(PK, FK_EMBARAZO)

--REVISIONPERSONAL(PK, FK_USUARIA)

--ESTADOANIMICO(PK)

--REVISIONPERSONAL-ESTADOANIMICO(PK (FK_REVISION, FK_ESTADO))
--REVISIONPERSONAL-SINTOMA (PK (FK_REVISION, FK_SINTOMA))

USE master
GO
CREATE DATABASE MenstruApp
GO

CREATE TABLE MEDICAMENTO(
	ID UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,

	CONSTRAINT PK_MEDICAMENTO PRIMARY KEY (ID)
)
GO

CREATE TABLE USUARIO (
	NICK NVARCHAR(25) NOT NULL,

	CONSTRAINT PK_USUARIO PRIMARY KEY (NICK)	
)
GO

CREATE TABLE MEDICAMENTO_USUARIO (
	ID_MEDICAMENTO UNIQUEIDENTIFIER NOT NULL,
	ID_USUARIO NVARCHAR(25) NOT NULL,

	CONSTRAINT FK_MEDICAMENTOUSUARIO_MEDICAMENTO FOREIGN KEY (ID_MEDICAMENTO)
	REFERENCES MEDICAMENTO(ID)
	ON DELETE NO ACTION ON UPDATE CASCADE,
	CONSTRAINT FK_MEDICAMENTOUSUARIO_USUARIO FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO(NICK)
	ON DELETE NO ACTION ON UPDATE CASCADE,
	CONSTRAINT PK_MEDICAMENTOUSUARIO PRIMARY KEY (ID_MEDICAMENTO, ID_USUARIO)

)
GO

CREATE TABLE CICLOMENSTRUAL (
	ID UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
	ID_USUARIO NVARCHAR(25) NOT NULL,

	CONSTRAINT PK_CICLOMENSTRUAL PRIMARY KEY (ID),
	CONSTRAINT FK_CICLOMENSTRUAL_USUARIO FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO(NICK)
	ON DELETE NO ACTION ON UPDATE CASCADE

)
GO

CREATE TABLE EMBARAZO (
	ID UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
	ID_USUARIO NVARCHAR(25) NOT NULL,

	CONSTRAINT PK_EMBARAZO PRIMARY KEY (ID),
	CONSTRAINT FK_EMBARAZO_USUARIO FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO(NICK)
	ON DELETE NO ACTION ON UPDATE CASCADE
)

