USE MenstruApp
GO

SELECT * FROM USUARIO

--INSERTAR USUARIO
insert into USUARIO (NICK, PASS) 
values('buhoos',PWDENCRYPT('12345678'))

--VERIFICAR LOGIN (SI DEVUELVE ALGUNA FILA, ES QUE ESTA OK)
select * from USUARIO where NICK ='buhoos' and PWDCOMPARE('12345678',PASS)= 1