package enumerado;

public enum EstadoAnimico {
    NULL, CALMADA, FELIZ, ENERGICA, ACTIVA, IRASCIBLE, IRRITADA, TRISTE, ANSIOSA, CULPABLE, DEPRIMIDA,
    OBSESIVA, APATICA, CONFUSA, EXIGENTE, DECAIDA, VULNERABLE, DESOLADA, SOLITARIA, IRACUNDA, MOLESTA,
    ENFADADA
}
