package enumerado;

public enum Sintoma {
    NULL, ME_ENCUENTRO_BIEN, DOLORES, PECHOS_SENSIBLES, DOLOR_DE_CABEZA, ACNE, DOLOR_DE_ESPALDA, NAUSEAS, FATIGA, HINCHAZON,
    ANTOJOS, INSOMNIO, ESTRENHIMIENTO, DIARREA, DOLOR_ABDOMINAL, DOLOR_EN_PERINEO, RETENCION_DE_LIQUIDOS, ESTRES
}
