/*INSERTAR DATOS EN LAS TABLAS DE 
SEXO, FLUJOVAGINAL, ESTADOANIMICO, SINTOMAS
*/
USE MENSTRUAPP
GO
INSERT INTO SEXO (OBSERVACION)
VALUES
('NO_HE_PRACTICADO_SEXO'),
('SEXO_CON_PROTECCION'),
('SEXO_SIN_PROTECCION'),
('DESEO_SEXUAL_ELEVADO'),
('MASTURBACION'),
('DESEO_SEXUAL_BAJO')
GO
SELECT * FROM SEXO
GO
INSERT INTO FLUJOVAGINAL(TIPO)
VALUES
('NADA_DE_FLUJO'),
('MANCHADO_INTERMENSTRUAL'),
('PEGAJOSO'),
('CREMOSO'),
('CLARA_DE_HUEVO'),
('AGUADO'),
('INUSUAL'),
('OTRO')
GO
SELECT * FROM FLUJOVAGINAL
GO

INSERT INTO SINTOMA(SINTOMA)
VALUES
('ME_ENCUENTRO_BIEN'),
('DOLORES'),
('PECHOS_SENSIBLES'),
('DOLOR_DE_CABEZA'),
('ACNE'),
('DOLOR_DE_ESPALDA'),
('NAUSEAS'),
('FATIGA'),
('HINCHAZON'),
('ANTOJOS'),
('INSOMNIO'),
('ESTRENHIMIENTO'),
('DIARREA'),
('DOLOR_ABDOMINAL'),
('DOLOR_EN_PERINEO'),
('RETENCION_DE_LIQUIDOS'),
('ESTRES')
GO
SELECT * FROM SINTOMA
GO
INSERT INTO ESTADOANIMICO(ESTADO)
VALUES
('CALMADA'),
('FELIZ'),
('ENERGICA'),
('ACTIVA'),
('IRASCIBLE'),
('IRRITADA'),
('TRISTE'),
('ANSIOSA'),
('CULPABLE'),
('DEPRIMIDA'),
('OBSESIVA'),
('APATICA'),
('CONFUSA'),
('EXIGENTE'),
('DECAIDA'),
('VULNERABLE'),
('DESOLADA'),
('SOLITARIA'),
('IRACUNDA'),
('MOLESTA'),
('ENFADADA')

GO
SELECT * FROM ESTADOANIMICO
GO