insert into MEDICAMENTO (NOMBRE) values ('Camilia');
insert into MEDICAMENTO (NOMBRE) values ('Phenazopyridine Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Silky Smooth Anti-Perspirant Deodorant');
insert into MEDICAMENTO (NOMBRE) values ('Neutrogena SkinClearing');
insert into MEDICAMENTO (NOMBRE) values ('Zosyn');
insert into MEDICAMENTO (NOMBRE) values ('Belladonna ex herba 6');
insert into MEDICAMENTO (NOMBRE) values ('Safe Sea Sunscreen With Jellyfish Sting Protective SPF 15');
insert into MEDICAMENTO (NOMBRE) values ('Strattera');
insert into MEDICAMENTO (NOMBRE) values ('Paecilomyces');
insert into MEDICAMENTO (NOMBRE) values ('Theophylline in Dextrose');
insert into MEDICAMENTO (NOMBRE) values ('Cold Complex');
insert into MEDICAMENTO (NOMBRE) values ('Fluocinonide');
insert into MEDICAMENTO (NOMBRE) values ('Benazepril Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Comfort Pac With Cyclobenzaprine');
insert into MEDICAMENTO (NOMBRE) values ('Select Brand Burn Relief');
insert into MEDICAMENTO (NOMBRE) values ('Groundsel');
insert into MEDICAMENTO (NOMBRE) values ('Sertraline Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Banana Boat Deep Tanning Dry SPF 8');
insert into MEDICAMENTO (NOMBRE) values ('Ondansetron');
insert into MEDICAMENTO (NOMBRE) values ('Tussin Cough');
insert into MEDICAMENTO (NOMBRE) values ('COREGCR');
insert into MEDICAMENTO (NOMBRE) values ('Triamcinolone Acetonide');
insert into MEDICAMENTO (NOMBRE) values ('Mucus Relief');
insert into MEDICAMENTO (NOMBRE) values ('Spironolactone');
insert into MEDICAMENTO (NOMBRE) values ('Nitrofurantoin');
insert into MEDICAMENTO (NOMBRE) values ('PURELL SF607 Instant Hand Sanitizing');
insert into MEDICAMENTO (NOMBRE) values ('Famciclovir');
insert into MEDICAMENTO (NOMBRE) values ('Fondaparinux Sodium');
insert into MEDICAMENTO (NOMBRE) values ('Azithromycin');
insert into MEDICAMENTO (NOMBRE) values ('Desquam-X Wash');
insert into MEDICAMENTO (NOMBRE) values ('Sotradecol');
insert into MEDICAMENTO (NOMBRE) values ('iBlanc Restora-Bright');
insert into MEDICAMENTO (NOMBRE) values ('GFA First Aid');
insert into MEDICAMENTO (NOMBRE) values ('Laxative');
insert into MEDICAMENTO (NOMBRE) values ('Oxygen');
insert into MEDICAMENTO (NOMBRE) values ('LEVETIRACETAM');
insert into MEDICAMENTO (NOMBRE) values ('SEROQUEL');
insert into MEDICAMENTO (NOMBRE) values ('50 Person ANSI');
insert into MEDICAMENTO (NOMBRE) values ('VERELAN PM');
insert into MEDICAMENTO (NOMBRE) values ('KERANIQUE For Women Hair Regrowth Treatment');
insert into MEDICAMENTO (NOMBRE) values ('DEXAMETHASONE');
insert into MEDICAMENTO (NOMBRE) values ('Diltiazem Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Progesterone');
insert into MEDICAMENTO (NOMBRE) values ('NEOMYCIN AND POLYMYXIN B SULFATES AND GRAMICIDIN');
insert into MEDICAMENTO (NOMBRE) values ('good sense cold remedy');
insert into MEDICAMENTO (NOMBRE) values ('Clorazepate Dipotassium');
insert into MEDICAMENTO (NOMBRE) values ('DEXTROSE');
insert into MEDICAMENTO (NOMBRE) values ('Omeprazole');
insert into MEDICAMENTO (NOMBRE) values ('Aricept');
insert into MEDICAMENTO (NOMBRE) values ('Rexall Vanishing Scent Pain Relieving');
insert into MEDICAMENTO (NOMBRE) values ('Valacyclovir Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Artichoke');
insert into MEDICAMENTO (NOMBRE) values ('HYDROQUINONE 4%');
insert into MEDICAMENTO (NOMBRE) values ('Progena');
insert into MEDICAMENTO (NOMBRE) values ('CLONIDINE HYDROCHLORIDE');
insert into MEDICAMENTO (NOMBRE) values ('Spironolactone');
insert into MEDICAMENTO (NOMBRE) values ('Amoxicillin');
insert into MEDICAMENTO (NOMBRE) values ('up and up acid controller complete');
insert into MEDICAMENTO (NOMBRE) values ('Divalproex Sodium');
insert into MEDICAMENTO (NOMBRE) values ('Lisinopril');
insert into MEDICAMENTO (NOMBRE) values ('CENTER-AL - POA PRATENSIS POLLEN');
insert into MEDICAMENTO (NOMBRE) values ('ALMOND');
insert into MEDICAMENTO (NOMBRE) values ('Orris Root');
insert into MEDICAMENTO (NOMBRE) values ('Asthma Plus');
insert into MEDICAMENTO (NOMBRE) values ('CARE ONE');
insert into MEDICAMENTO (NOMBRE) values ('Gelato APF');
insert into MEDICAMENTO (NOMBRE) values ('Rhus tox. 1 Special Order');
insert into MEDICAMENTO (NOMBRE) values ('Sun Beige Perfecting Makeup Broad Spectrum SPF 25');
insert into MEDICAMENTO (NOMBRE) values ('Alpet E3 Plus Hand Sanitizer Spray');
insert into MEDICAMENTO (NOMBRE) values ('EpiSoft');
insert into MEDICAMENTO (NOMBRE) values ('Rizatriptan Benzoate');
insert into MEDICAMENTO (NOMBRE) values ('Mometasone Furoate');
insert into MEDICAMENTO (NOMBRE) values ('Treatment Set TS338384');
insert into MEDICAMENTO (NOMBRE) values ('Trinatal GT');
insert into MEDICAMENTO (NOMBRE) values ('Sulfamethoxazole and Trimethoprim');
insert into MEDICAMENTO (NOMBRE) values ('Thuja Occidentalis Kit Refill');
insert into MEDICAMENTO (NOMBRE) values ('Pain Reliever Fever Reducer');
insert into MEDICAMENTO (NOMBRE) values ('METHADONE HYDROCHLORIDE');
insert into MEDICAMENTO (NOMBRE) values ('Rocky Mountain Sunscreen');
insert into MEDICAMENTO (NOMBRE) values ('FELODIPINE');
insert into MEDICAMENTO (NOMBRE) values ('Olanzapine');
insert into MEDICAMENTO (NOMBRE) values ('Nix Complete Maximum Strength Lice Elimination');
insert into MEDICAMENTO (NOMBRE) values ('Benztropine Mesylate');
insert into MEDICAMENTO (NOMBRE) values ('Escitalopram');
insert into MEDICAMENTO (NOMBRE) values ('3 CONCEPT EYES LIQUID FOUNDATION IVORY BEIGE');
insert into MEDICAMENTO (NOMBRE) values ('Phylorinol');
insert into MEDICAMENTO (NOMBRE) values ('Lisinopril');
insert into MEDICAMENTO (NOMBRE) values ('Glyburide');
insert into MEDICAMENTO (NOMBRE) values ('Clodan Kit');
insert into MEDICAMENTO (NOMBRE) values ('Bisoprolol Fumarate and Hydrochlorothiazide');
insert into MEDICAMENTO (NOMBRE) values ('Butalbital, Acetaminophen, and Caffeine');
insert into MEDICAMENTO (NOMBRE) values ('Glumetza');
insert into MEDICAMENTO (NOMBRE) values ('Maprotiline Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Ampicillin and Sulbactam');
insert into MEDICAMENTO (NOMBRE) values ('Bryonia Stannum');
insert into MEDICAMENTO (NOMBRE) values ('Nefazodone Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Coconut');
insert into MEDICAMENTO (NOMBRE) values ('OAT');
insert into MEDICAMENTO (NOMBRE) values ('dg health heartburn prevention');
insert into MEDICAMENTO (NOMBRE) values ('Amoxicillin');
insert into MEDICAMENTO (NOMBRE) values ('Tamsulosin Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('AZITHROMYCIN');
insert into MEDICAMENTO (NOMBRE) values ('Midazolam Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('FLORIL TEARS');
insert into MEDICAMENTO (NOMBRE) values ('Oxilan');
insert into MEDICAMENTO (NOMBRE) values ('PhytoGel');
insert into MEDICAMENTO (NOMBRE) values ('GaviLyte G');
insert into MEDICAMENTO (NOMBRE) values ('Ceftriaxone Sodium');
insert into MEDICAMENTO (NOMBRE) values ('METROGEL');
insert into MEDICAMENTO (NOMBRE) values ('Isopropyl Alcohol');
insert into MEDICAMENTO (NOMBRE) values ('CANIS LUPUS FAMILIARIS SKIN');
insert into MEDICAMENTO (NOMBRE) values ('Pantoprazole Sodium');
insert into MEDICAMENTO (NOMBRE) values ('Nasal Relief');
insert into MEDICAMENTO (NOMBRE) values ('Tourmaline Formica comp. Special Order');
insert into MEDICAMENTO (NOMBRE) values ('Diclofenac Sodium');
insert into MEDICAMENTO (NOMBRE) values ('Ifosfamide');
insert into MEDICAMENTO (NOMBRE) values ('Metoprolol Tartrate');
insert into MEDICAMENTO (NOMBRE) values ('Golden Pear Antibacterial Foaming Hand Wash');
insert into MEDICAMENTO (NOMBRE) values ('Trichophyton Mixture');
insert into MEDICAMENTO (NOMBRE) values ('esika');
insert into MEDICAMENTO (NOMBRE) values ('Bioelements');
insert into MEDICAMENTO (NOMBRE) values ('Mucus Relief PE');
insert into MEDICAMENTO (NOMBRE) values ('North Alcohol Wipe');
insert into MEDICAMENTO (NOMBRE) values ('PhysiciansCare Dimenhydrinate');
insert into MEDICAMENTO (NOMBRE) values ('Severe Sinus Congestion and Pain Daytime');
insert into MEDICAMENTO (NOMBRE) values ('Vital Male Sexual Energy');
insert into MEDICAMENTO (NOMBRE) values ('Oxygen');
insert into MEDICAMENTO (NOMBRE) values ('Promethazine with Codeine');
insert into MEDICAMENTO (NOMBRE) values ('Hydromorphone HCl');
insert into MEDICAMENTO (NOMBRE) values ('CC Cream Complexion Corrector Medium Dark Broad Spectrum SPF 15');
insert into MEDICAMENTO (NOMBRE) values ('Nausea Vomiting');
insert into MEDICAMENTO (NOMBRE) values ('Losartan Potassium');
insert into MEDICAMENTO (NOMBRE) values ('Bupropion Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Lacrisert');
insert into MEDICAMENTO (NOMBRE) values ('Equate Nicotine');
insert into MEDICAMENTO (NOMBRE) values ('Bacitracin Zinc');
insert into MEDICAMENTO (NOMBRE) values ('Verapamil Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Ranitidine 75');
insert into MEDICAMENTO (NOMBRE) values ('Cefprozil');
insert into MEDICAMENTO (NOMBRE) values ('Temozolomide');
insert into MEDICAMENTO (NOMBRE) values ('Childrens Mucinex');
insert into MEDICAMENTO (NOMBRE) values ('SMART SENSE');
insert into MEDICAMENTO (NOMBRE) values ('Clearasil Ultra');
insert into MEDICAMENTO (NOMBRE) values ('SHISEIDO ADVANCED HYDRO-LIQUID COMPACT (REFILL)');
insert into MEDICAMENTO (NOMBRE) values ('Risperidone');
insert into MEDICAMENTO (NOMBRE) values ('Childrens Allergy Relief');
insert into MEDICAMENTO (NOMBRE) values ('TriLipiderm');
insert into MEDICAMENTO (NOMBRE) values ('Ban');
insert into MEDICAMENTO (NOMBRE) values ('Lovenox');
insert into MEDICAMENTO (NOMBRE) values ('TUMS');
insert into MEDICAMENTO (NOMBRE) values ('Aveeno Baby Organic Harvest Diaper Rash');
insert into MEDICAMENTO (NOMBRE) values ('Papaya');
insert into MEDICAMENTO (NOMBRE) values ('Diltiazem Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Covergirl Outlast Stay Fabulous 3in1 Foundation');
insert into MEDICAMENTO (NOMBRE) values ('Aspirin');
insert into MEDICAMENTO (NOMBRE) values ('CVS daily moisturizing');
insert into MEDICAMENTO (NOMBRE) values ('SOLIE EMULSION');
insert into MEDICAMENTO (NOMBRE) values ('Adult Low Dose Enteric Coated Aspirin');
insert into MEDICAMENTO (NOMBRE) values ('LETROZOLE');
insert into MEDICAMENTO (NOMBRE) values ('Care One Pain Relief');
insert into MEDICAMENTO (NOMBRE) values ('Chlorpheniramine maleate');
insert into MEDICAMENTO (NOMBRE) values ('LONG LAST GLOSSWEAR');
insert into MEDICAMENTO (NOMBRE) values ('Gentamicin Sulfate in Sodium Chloride');
insert into MEDICAMENTO (NOMBRE) values ('LBel');
insert into MEDICAMENTO (NOMBRE) values ('Allergy Relief');
insert into MEDICAMENTO (NOMBRE) values ('XEROSTOM');
insert into MEDICAMENTO (NOMBRE) values ('PRAVASTATIN SODIUM');
insert into MEDICAMENTO (NOMBRE) values ('ADVAIR');
insert into MEDICAMENTO (NOMBRE) values ('LOSARTAN POTASSIUM');
insert into MEDICAMENTO (NOMBRE) values ('AVANDAMET');
insert into MEDICAMENTO (NOMBRE) values ('Personal Care Petroleum Jelly Skin Protectant');
insert into MEDICAMENTO (NOMBRE) values ('Kapok');
insert into MEDICAMENTO (NOMBRE) values ('Citalopram Hydrobromide');
insert into MEDICAMENTO (NOMBRE) values ('Exuviance CoverBlend Concealing Treatment Makeup');
insert into MEDICAMENTO (NOMBRE) values ('Anti Diarrheal');
insert into MEDICAMENTO (NOMBRE) values ('Prefera OB plus DHA');
insert into MEDICAMENTO (NOMBRE) values ('Zonisamide');
insert into MEDICAMENTO (NOMBRE) values ('nighttime');
insert into MEDICAMENTO (NOMBRE) values ('pain relief');
insert into MEDICAMENTO (NOMBRE) values ('Reserpine');
insert into MEDICAMENTO (NOMBRE) values ('Intervene Daily Moisture SPF 15 Oil Free');
insert into MEDICAMENTO (NOMBRE) values ('Nitrous Oxide');
insert into MEDICAMENTO (NOMBRE) values ('Lactated Ringers');
insert into MEDICAMENTO (NOMBRE) values ('BANDAGE');
insert into MEDICAMENTO (NOMBRE) values ('MEDICAL AIR');
insert into MEDICAMENTO (NOMBRE) values ('Meijer');
insert into MEDICAMENTO (NOMBRE) values ('Tendon Rescue');
insert into MEDICAMENTO (NOMBRE) values ('ACD-A');
insert into MEDICAMENTO (NOMBRE) values ('Dorzolamide Hydrochloride and Timolol Maleate');
insert into MEDICAMENTO (NOMBRE) values ('Lidocaine Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Oxycodone and Acetaminophen');
insert into MEDICAMENTO (NOMBRE) values ('Omeprazole');
insert into MEDICAMENTO (NOMBRE) values ('Olanzapine');
insert into MEDICAMENTO (NOMBRE) values ('Actos');
insert into MEDICAMENTO (NOMBRE) values ('Oxygen');
insert into MEDICAMENTO (NOMBRE) values ('Levothyroxine Sodium');
insert into MEDICAMENTO (NOMBRE) values ('Simvastatin');
insert into MEDICAMENTO (NOMBRE) values ('Losartan Potassium');
insert into MEDICAMENTO (NOMBRE) values ('ADVENTURE MEDICAL KITS 1-4 PERSON FIRST AID');
insert into MEDICAMENTO (NOMBRE) values ('Opium tincture deodorized');
insert into MEDICAMENTO (NOMBRE) values ('Senna S');
insert into MEDICAMENTO (NOMBRE) values ('RANITIDINE');
insert into MEDICAMENTO (NOMBRE) values ('Oxcarbazepine');
insert into MEDICAMENTO (NOMBRE) values ('CENTER-AL - SORGHUM HALEPENSE POLLEN');
insert into MEDICAMENTO (NOMBRE) values ('Indomethacin');
insert into MEDICAMENTO (NOMBRE) values ('acetaminophen');
insert into MEDICAMENTO (NOMBRE) values ('Exforge HCT');
insert into MEDICAMENTO (NOMBRE) values ('Staphysagria Kit Refill');
insert into MEDICAMENTO (NOMBRE) values ('Vicks DayQuil');
insert into MEDICAMENTO (NOMBRE) values ('SHISEIDO SHEER AND PERFECT FOUNDATION');
insert into MEDICAMENTO (NOMBRE) values ('Plan B');
insert into MEDICAMENTO (NOMBRE) values ('Celadrin');
insert into MEDICAMENTO (NOMBRE) values ('KETAMINE HYDROCHLORIDE');
insert into MEDICAMENTO (NOMBRE) values ('Phylorinol');
insert into MEDICAMENTO (NOMBRE) values ('Pleo Chelate');
insert into MEDICAMENTO (NOMBRE) values ('Estradiol');
insert into MEDICAMENTO (NOMBRE) values ('Dextrose And Sodium Chloride');
insert into MEDICAMENTO (NOMBRE) values ('Mary Kay Tinted Lip Balm Sunscreen SPF 15 Rose');
insert into MEDICAMENTO (NOMBRE) values ('Benazepril Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Fluocinolone Acetonide');
insert into MEDICAMENTO (NOMBRE) values ('Hydrocodone Bitartrate And Acetaminophen');
insert into MEDICAMENTO (NOMBRE) values ('Dexamethasone');
insert into MEDICAMENTO (NOMBRE) values ('No7 Time Resisting Day Cream Sunscreen SPF 12');
insert into MEDICAMENTO (NOMBRE) values ('AAPE Hair Ampoule');
insert into MEDICAMENTO (NOMBRE) values ('Onopordon Aurum Special Order');
insert into MEDICAMENTO (NOMBRE) values ('TOPCARE');
insert into MEDICAMENTO (NOMBRE) values ('Bacteriostatic Water');
insert into MEDICAMENTO (NOMBRE) values ('Methyldopa');
insert into MEDICAMENTO (NOMBRE) values ('Ciprofloxacin');
insert into MEDICAMENTO (NOMBRE) values ('ESIKA');
insert into MEDICAMENTO (NOMBRE) values ('Pantoprazole');
insert into MEDICAMENTO (NOMBRE) values ('ADD');
insert into MEDICAMENTO (NOMBRE) values ('Glipizide');
insert into MEDICAMENTO (NOMBRE) values ('Prednisone');
insert into MEDICAMENTO (NOMBRE) values ('TC EnrichedFoam');
insert into MEDICAMENTO (NOMBRE) values ('verapamil hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Diltiazem Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Venlafaxine Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Loperamide Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('SAMSCA');
insert into MEDICAMENTO (NOMBRE) values ('Lansoprazole');
insert into MEDICAMENTO (NOMBRE) values ('Walgreens Chap Aid Regular Lip Balm');
insert into MEDICAMENTO (NOMBRE) values ('Topcare Cough and Sore Throat');
insert into MEDICAMENTO (NOMBRE) values ('Naltrexone Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Medicated Pain');
insert into MEDICAMENTO (NOMBRE) values ('HYDROCODONE BITARTRATE AND ACETAMINOPHEN');
insert into MEDICAMENTO (NOMBRE) values ('SudoGest');
insert into MEDICAMENTO (NOMBRE) values ('SNAIL THERAPY 50 BB');
insert into MEDICAMENTO (NOMBRE) values ('Perrigo Prednisone');
insert into MEDICAMENTO (NOMBRE) values ('Hydrocodone Bitartrate and Acetaminophen');
insert into MEDICAMENTO (NOMBRE) values ('Alprazolam');
insert into MEDICAMENTO (NOMBRE) values ('equate childrens cold and cough');
insert into MEDICAMENTO (NOMBRE) values ('CAPASTAT SULFATE');
insert into MEDICAMENTO (NOMBRE) values ('Ibuprofen');
insert into MEDICAMENTO (NOMBRE) values ('Metoprolol Tartrate and Hydrochlorothiazide');
insert into MEDICAMENTO (NOMBRE) values ('Tekamlo');
insert into MEDICAMENTO (NOMBRE) values ('Lymph Drainage');
insert into MEDICAMENTO (NOMBRE) values ('Atenolol');
insert into MEDICAMENTO (NOMBRE) values ('Paire OB Plus DHA');
insert into MEDICAMENTO (NOMBRE) values ('Gabapentin');
insert into MEDICAMENTO (NOMBRE) values ('Pramipexole Dihydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Oxalis e pl. tota 3');
insert into MEDICAMENTO (NOMBRE) values ('olio activ mouthwash');
insert into MEDICAMENTO (NOMBRE) values ('Oxygen');
insert into MEDICAMENTO (NOMBRE) values ('LITHOBID');
insert into MEDICAMENTO (NOMBRE) values ('Metaxalone');
insert into MEDICAMENTO (NOMBRE) values ('Nystatin');
insert into MEDICAMENTO (NOMBRE) values ('MAYFAIR HAND SANITIZING WIPES WITH ALOE');
insert into MEDICAMENTO (NOMBRE) values ('INVEGA');
insert into MEDICAMENTO (NOMBRE) values ('Potassium Chloride');
insert into MEDICAMENTO (NOMBRE) values ('Diabetic Tussin Nighttime Cold and Flu');
insert into MEDICAMENTO (NOMBRE) values ('Blue Beech (Hornbeam)');
insert into MEDICAMENTO (NOMBRE) values ('Complete Beauty');
insert into MEDICAMENTO (NOMBRE) values ('Neosporin Original');
insert into MEDICAMENTO (NOMBRE) values ('ziprasidone hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Demerol');
insert into MEDICAMENTO (NOMBRE) values ('Ciprofloxacin');
insert into MEDICAMENTO (NOMBRE) values ('Ibuprofen');
insert into MEDICAMENTO (NOMBRE) values ('Pylera');
insert into MEDICAMENTO (NOMBRE) values ('Primidone');
insert into MEDICAMENTO (NOMBRE) values ('Levemir');
insert into MEDICAMENTO (NOMBRE) values ('fexofenadine hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Lyme HP');
insert into MEDICAMENTO (NOMBRE) values ('All Day Allergy');
insert into MEDICAMENTO (NOMBRE) values ('Amoxicillin');
insert into MEDICAMENTO (NOMBRE) values ('Neomycin and Polymyxin B Sulfates and Dexamethasone');
insert into MEDICAMENTO (NOMBRE) values ('Topcare nicotine');
insert into MEDICAMENTO (NOMBRE) values ('Lamotrigine');
insert into MEDICAMENTO (NOMBRE) values ('Daytime Nighttime Cold Flu Relief');
insert into MEDICAMENTO (NOMBRE) values ('Select Brand Antacid Assorted Berries');
insert into MEDICAMENTO (NOMBRE) values ('CENTER-AL - HOUSE DUST');
insert into MEDICAMENTO (NOMBRE) values ('Rasuvo');
insert into MEDICAMENTO (NOMBRE) values ('Category I');
insert into MEDICAMENTO (NOMBRE) values ('Theratramadol-90');
insert into MEDICAMENTO (NOMBRE) values ('Flu Tonic');
insert into MEDICAMENTO (NOMBRE) values ('VALACYCLOVIR HYDROCHLORIDE');
insert into MEDICAMENTO (NOMBRE) values ('sore throat');
insert into MEDICAMENTO (NOMBRE) values ('Head and Shoulders');
insert into MEDICAMENTO (NOMBRE) values ('Buspirone hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Opana');
insert into MEDICAMENTO (NOMBRE) values ('Exuviance CoverBlend Concealing Treatment Makeup');
insert into MEDICAMENTO (NOMBRE) values ('Ofloxacin');
insert into MEDICAMENTO (NOMBRE) values ('PHOMA EXIGUA VAR EXIGUA');
insert into MEDICAMENTO (NOMBRE) values ('Body');
insert into MEDICAMENTO (NOMBRE) values ('POPULUS DELTOIDES SSP MONILIFERA POLLEN');
insert into MEDICAMENTO (NOMBRE) values ('TIAGABINE HYDROCHLORIDE');
insert into MEDICAMENTO (NOMBRE) values ('DUAL ACTION CHERRY COUGH SUPPRESSANT ORAL ANESTHETIC');
insert into MEDICAMENTO (NOMBRE) values ('Intelence');
insert into MEDICAMENTO (NOMBRE) values ('BZK Towelette');
insert into MEDICAMENTO (NOMBRE) values ('SESAME SEED');
insert into MEDICAMENTO (NOMBRE) values ('TOPROLXL');
insert into MEDICAMENTO (NOMBRE) values ('Whitening Foaming-Toothpaste');
insert into MEDICAMENTO (NOMBRE) values ('PARAID One Step Wart Remover Strips');
insert into MEDICAMENTO (NOMBRE) values ('Alendronate Sodium');
insert into MEDICAMENTO (NOMBRE) values ('Bethanechol Chloride');
insert into MEDICAMENTO (NOMBRE) values ('LOreal Paris True Match Lumi Healthy Luminous Makeup Broad Spectrum SPF 20');
insert into MEDICAMENTO (NOMBRE) values ('RX200 Foaming Instant Hand Sanitizer');
insert into MEDICAMENTO (NOMBRE) values ('Hydrocodone Bitartrate and Acetaminophen');
insert into MEDICAMENTO (NOMBRE) values ('pseudoephedrine hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Prometh with Codeine');
insert into MEDICAMENTO (NOMBRE) values ('Anagrelide Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Childrens Chewable Aspirin');
insert into MEDICAMENTO (NOMBRE) values ('MINERAL FOUNDATION');
insert into MEDICAMENTO (NOMBRE) values ('SPONGIA TOSTA');
insert into MEDICAMENTO (NOMBRE) values ('The Cover Classic Pro Foundation');
insert into MEDICAMENTO (NOMBRE) values ('Fluconazole');
insert into MEDICAMENTO (NOMBRE) values ('hydroxyzine pamoate');
insert into MEDICAMENTO (NOMBRE) values ('Horse Epithelium');
insert into MEDICAMENTO (NOMBRE) values ('PHENERGAN');
insert into MEDICAMENTO (NOMBRE) values ('Vancomycin Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Bacitracin Zinc');
insert into MEDICAMENTO (NOMBRE) values ('CAPTOPRIL');
insert into MEDICAMENTO (NOMBRE) values ('Childrens Mucinex');
insert into MEDICAMENTO (NOMBRE) values ('MINI HAND SANITIZER - ORANGE AND LEMON');
insert into MEDICAMENTO (NOMBRE) values ('careone pain relief');
insert into MEDICAMENTO (NOMBRE) values ('Doxercalciferol');
insert into MEDICAMENTO (NOMBRE) values ('PreviDent 5000 Enamel Protect');
insert into MEDICAMENTO (NOMBRE) values ('Lisinopril');
insert into MEDICAMENTO (NOMBRE) values ('Levothyroxine Sodium');
insert into MEDICAMENTO (NOMBRE) values ('HEMORRHOIDS');
insert into MEDICAMENTO (NOMBRE) values ('MINOXIDIL');
insert into MEDICAMENTO (NOMBRE) values ('SINGULAIR');
insert into MEDICAMENTO (NOMBRE) values ('Hot Ice Soothing Analgesic Gel');
insert into MEDICAMENTO (NOMBRE) values ('MINI HAND SANITIZER - ORANGE AND LEMON');
insert into MEDICAMENTO (NOMBRE) values ('Roxalia');
insert into MEDICAMENTO (NOMBRE) values ('ESIKA');
insert into MEDICAMENTO (NOMBRE) values ('CEFTRIAXONE');
insert into MEDICAMENTO (NOMBRE) values ('Sheer Cover Mineral Foundation');
insert into MEDICAMENTO (NOMBRE) values ('Ciclodan');
insert into MEDICAMENTO (NOMBRE) values ('Silky Smooth Anti-Perspirant Deodorant');
insert into MEDICAMENTO (NOMBRE) values ('Dr. Scholls');
insert into MEDICAMENTO (NOMBRE) values ('Valsartan and Hydrochlorothiazide');
insert into MEDICAMENTO (NOMBRE) values ('Laxative');
insert into MEDICAMENTO (NOMBRE) values ('Tahitian Noni');
insert into MEDICAMENTO (NOMBRE) values ('DAMOAE THERAPY');
insert into MEDICAMENTO (NOMBRE) values ('Hydrocortisone');
insert into MEDICAMENTO (NOMBRE) values ('Jute');
insert into MEDICAMENTO (NOMBRE) values ('Terrasil Rapid-Relief Vaginal');
insert into MEDICAMENTO (NOMBRE) values ('Irbesartan');
insert into MEDICAMENTO (NOMBRE) values ('Phenazopyridine Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Vancomycin Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Nortriptyline Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Enviroclenz');
insert into MEDICAMENTO (NOMBRE) values ('aspirin');
insert into MEDICAMENTO (NOMBRE) values ('Anti-Diarrheal');
insert into MEDICAMENTO (NOMBRE) values ('NWI ORIGINAL');
insert into MEDICAMENTO (NOMBRE) values ('Thyroplex');
insert into MEDICAMENTO (NOMBRE) values ('CLINIMIX');
insert into MEDICAMENTO (NOMBRE) values ('ALCOHOL FREE HAND SANITIZER');
insert into MEDICAMENTO (NOMBRE) values ('Diphenhydramine Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Infants Ibuprofen');
insert into MEDICAMENTO (NOMBRE) values ('Lidocaine Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Carbidopa and levodopa');
insert into MEDICAMENTO (NOMBRE) values ('Nisoldipine');
insert into MEDICAMENTO (NOMBRE) values ('smart sense nasal');
insert into MEDICAMENTO (NOMBRE) values ('Phendimetrazine Tartrate');
insert into MEDICAMENTO (NOMBRE) values ('Phenylephrine Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('MEDI-PATCH');
insert into MEDICAMENTO (NOMBRE) values ('harmon face values omeprazole');
insert into MEDICAMENTO (NOMBRE) values ('Amlodipine besylate and Atorvastatin calcium');
insert into MEDICAMENTO (NOMBRE) values ('Ketorolac Tromethamine');
insert into MEDICAMENTO (NOMBRE) values ('Testosterone Cypionate');
insert into MEDICAMENTO (NOMBRE) values ('ELOCON');
insert into MEDICAMENTO (NOMBRE) values ('Carbamazepine');
insert into MEDICAMENTO (NOMBRE) values ('Acebutolol Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Flawless Finish Bare Perfection Makeup SPF 8 Beige');
insert into MEDICAMENTO (NOMBRE) values ('FACE VALUES TRIPLE ANTIBIOTIC');
insert into MEDICAMENTO (NOMBRE) values ('Cephalexin');
insert into MEDICAMENTO (NOMBRE) values ('DIPHENHYDRAMINE HYDROCHLORIDE');
insert into MEDICAMENTO (NOMBRE) values ('Lisinopril');
insert into MEDICAMENTO (NOMBRE) values ('Genitrex');
insert into MEDICAMENTO (NOMBRE) values ('JUNIPERUS VIRGINIANA POLLEN');
insert into MEDICAMENTO (NOMBRE) values ('Entre-S');
insert into MEDICAMENTO (NOMBRE) values ('metformin hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Warm Ginger Always color stay-on Makeup Broad Spectrum SPF 15');
insert into MEDICAMENTO (NOMBRE) values ('Promethazine Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('all day relief');
insert into MEDICAMENTO (NOMBRE) values ('Oxazepam');
insert into MEDICAMENTO (NOMBRE) values ('Caffeine Citrate');
insert into MEDICAMENTO (NOMBRE) values ('Headaches');
insert into MEDICAMENTO (NOMBRE) values ('WHITE OAK POLLEN');
insert into MEDICAMENTO (NOMBRE) values ('Glyburide and Metformin');
insert into MEDICAMENTO (NOMBRE) values ('Diazepam');
insert into MEDICAMENTO (NOMBRE) values ('Ranitidine Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('OXYGEN');
insert into MEDICAMENTO (NOMBRE) values ('clindamycin phosphate');
insert into MEDICAMENTO (NOMBRE) values ('Mosquito');
insert into MEDICAMENTO (NOMBRE) values ('Medicated Acne Pads');
insert into MEDICAMENTO (NOMBRE) values ('Dermaquest Skin Therapy Solar Protection SPF 15');
insert into MEDICAMENTO (NOMBRE) values ('Mucus Relief Cold and Sinus');
insert into MEDICAMENTO (NOMBRE) values ('Enoxaparin Sodium');
insert into MEDICAMENTO (NOMBRE) values ('Sandy Beige Expert Finish Makeup Makeup Broad Spectrum SPF 25');
insert into MEDICAMENTO (NOMBRE) values ('Sunmark fiber laxative');
insert into MEDICAMENTO (NOMBRE) values ('DocQLax');
insert into MEDICAMENTO (NOMBRE) values ('Levetiracetam');
insert into MEDICAMENTO (NOMBRE) values ('Mimvey');
insert into MEDICAMENTO (NOMBRE) values ('Lamotrigine');
insert into MEDICAMENTO (NOMBRE) values ('Metoprolol Tartrate');
insert into MEDICAMENTO (NOMBRE) values ('Vancomycin Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Haloperidol');
insert into MEDICAMENTO (NOMBRE) values ('Cat Pelt, Standardized');
insert into MEDICAMENTO (NOMBRE) values ('Daytime Cold and Flu Relief');
insert into MEDICAMENTO (NOMBRE) values ('good neighbor pharmacy nasal decongestant');
insert into MEDICAMENTO (NOMBRE) values ('LIQUIDAMBAR STYRACIFLUA POLLEN');
insert into MEDICAMENTO (NOMBRE) values ('Cosyntropin');
insert into MEDICAMENTO (NOMBRE) values ('Ramipril');
insert into MEDICAMENTO (NOMBRE) values ('healthy accents sinus');
insert into MEDICAMENTO (NOMBRE) values ('Levothyroxine sodium');
insert into MEDICAMENTO (NOMBRE) values ('PRAMOSONE');
insert into MEDICAMENTO (NOMBRE) values ('Diovan HCT');
insert into MEDICAMENTO (NOMBRE) values ('Temovate');
insert into MEDICAMENTO (NOMBRE) values ('Cold Cough');
insert into MEDICAMENTO (NOMBRE) values ('Minoxidil');
insert into MEDICAMENTO (NOMBRE) values ('Mustard Seed');
insert into MEDICAMENTO (NOMBRE) values ('MANGO BUTTER LIPSTICK');
insert into MEDICAMENTO (NOMBRE) values ('Therapeutic Sulfur Mask');
insert into MEDICAMENTO (NOMBRE) values ('Theophylline');
insert into MEDICAMENTO (NOMBRE) values ('PINUS ECHINATA POLLEN');
insert into MEDICAMENTO (NOMBRE) values ('Oxacillin');
insert into MEDICAMENTO (NOMBRE) values ('BAROX');
insert into MEDICAMENTO (NOMBRE) values ('No Foundation SPF 30');
insert into MEDICAMENTO (NOMBRE) values ('YUN XIANG JING');
insert into MEDICAMENTO (NOMBRE) values ('Loprox');
insert into MEDICAMENTO (NOMBRE) values ('Blistex');
insert into MEDICAMENTO (NOMBRE) values ('Amlodipine Besylate and Benazepril Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Ondansetron Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('BUPROPION HYDROCHLORIDE');
insert into MEDICAMENTO (NOMBRE) values ('Dexamethasone');
insert into MEDICAMENTO (NOMBRE) values ('EROS AQUA SENSATIONS AND CARE');
insert into MEDICAMENTO (NOMBRE) values ('Sunkissed Honeydew Hand Sanitizer');
insert into MEDICAMENTO (NOMBRE) values ('Warfarin Sodium');
insert into MEDICAMENTO (NOMBRE) values ('MUM CHAMOMILE');
insert into MEDICAMENTO (NOMBRE) values ('Prednisone');
insert into MEDICAMENTO (NOMBRE) values ('Purminerals 4-in-1 14-Hour Wear Foundation Broad Spectrum SPF 15 (GOLDEN DARK)');
insert into MEDICAMENTO (NOMBRE) values ('Oxcarbazepine');
insert into MEDICAMENTO (NOMBRE) values ('ESSENTIAL SOLUTION CAVIAR MASK SHEET');
insert into MEDICAMENTO (NOMBRE) values ('Atorvastatin Calcium');
insert into MEDICAMENTO (NOMBRE) values ('Preferred Plus Loperamide Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('FORANE');
insert into MEDICAMENTO (NOMBRE) values ('Witch Hazel');
insert into MEDICAMENTO (NOMBRE) values ('Amlodipine besylate and Atorvastatin calcium');
insert into MEDICAMENTO (NOMBRE) values ('Acetaminophen');
insert into MEDICAMENTO (NOMBRE) values ('ShopKo Absolute Daily Moisturizing Broad Spectrum SPF15 Sunscreen');
insert into MEDICAMENTO (NOMBRE) values ('Bronci');
insert into MEDICAMENTO (NOMBRE) values ('Rapid Comfort Non Aspirin');
insert into MEDICAMENTO (NOMBRE) values ('REPAIRWEAR LIFT');
insert into MEDICAMENTO (NOMBRE) values ('Iodine Bush');
insert into MEDICAMENTO (NOMBRE) values ('LOLIUM PERENNE SSP MULTIFLORUM POLLEN');
insert into MEDICAMENTO (NOMBRE) values ('Cockroach American');
insert into MEDICAMENTO (NOMBRE) values ('Magnolia Blossom Scented Hand Sanitizer Anti-Bacterial');
insert into MEDICAMENTO (NOMBRE) values ('Shopko Antibacterial Foaming Hand Sanitizer');
insert into MEDICAMENTO (NOMBRE) values ('Medicated Acne Pads');
insert into MEDICAMENTO (NOMBRE) values ('Methocarbamol');
insert into MEDICAMENTO (NOMBRE) values ('Ranitidine');
insert into MEDICAMENTO (NOMBRE) values ('NIGHT-TIME');
insert into MEDICAMENTO (NOMBRE) values ('CAREONE');
insert into MEDICAMENTO (NOMBRE) values ('Isopropyl Rubbing Alcohol 50% With Wintergreen');
insert into MEDICAMENTO (NOMBRE) values ('Red Mulberry');
insert into MEDICAMENTO (NOMBRE) values ('AZITHROMYCIN');
insert into MEDICAMENTO (NOMBRE) values ('expectorant');
insert into MEDICAMENTO (NOMBRE) values ('Adult Low Strength Aspirin');
insert into MEDICAMENTO (NOMBRE) values ('Fentanyl');
insert into MEDICAMENTO (NOMBRE) values ('Dove');
insert into MEDICAMENTO (NOMBRE) values ('Promethazine Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Stool Softener');
insert into MEDICAMENTO (NOMBRE) values ('DE LA CRUZ SODIUM BICARBONATE ANTACID');
insert into MEDICAMENTO (NOMBRE) values ('Diphenhydramine Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('EDECRIN');
insert into MEDICAMENTO (NOMBRE) values ('smart sense flu and severe cold and cough');
insert into MEDICAMENTO (NOMBRE) values ('DAILY MOISTURIZING');
insert into MEDICAMENTO (NOMBRE) values ('C Mold Mixture');
insert into MEDICAMENTO (NOMBRE) values ('BuPROPion Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Anti-Diarrheal');
insert into MEDICAMENTO (NOMBRE) values ('Ciprofloxacin');
insert into MEDICAMENTO (NOMBRE) values ('Duloxetine Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Metronidazole');
insert into MEDICAMENTO (NOMBRE) values ('Hemorrhoids');
insert into MEDICAMENTO (NOMBRE) values ('Piroxicam');
insert into MEDICAMENTO (NOMBRE) values ('Grapefruit');
insert into MEDICAMENTO (NOMBRE) values ('Baclofen');
insert into MEDICAMENTO (NOMBRE) values ('MediChoice PVP Swabsticks');
insert into MEDICAMENTO (NOMBRE) values ('Lorazepam');
insert into MEDICAMENTO (NOMBRE) values ('Freds Chest Congestion Relief');
insert into MEDICAMENTO (NOMBRE) values ('California Live Oak');
insert into MEDICAMENTO (NOMBRE) values ('Citalopram');
insert into MEDICAMENTO (NOMBRE) values ('Acid Free-Flux');
insert into MEDICAMENTO (NOMBRE) values ('Preferred Plus TabTussin');
insert into MEDICAMENTO (NOMBRE) values ('Pleo Ut S');
insert into MEDICAMENTO (NOMBRE) values ('Risperidone');
insert into MEDICAMENTO (NOMBRE) values ('GEMFIBROZIL');
insert into MEDICAMENTO (NOMBRE) values ('Gabapentin');
insert into MEDICAMENTO (NOMBRE) values ('Lacura Invisible Solid Shower Fresh');
insert into MEDICAMENTO (NOMBRE) values ('Gabapentin');
insert into MEDICAMENTO (NOMBRE) values ('Atrovent');
insert into MEDICAMENTO (NOMBRE) values ('Glipizide');
insert into MEDICAMENTO (NOMBRE) values ('TretinX');
insert into MEDICAMENTO (NOMBRE) values ('Metformin Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('headache formula');
insert into MEDICAMENTO (NOMBRE) values ('Anti-Clog Concentrate');
insert into MEDICAMENTO (NOMBRE) values ('Baby Teething Oral Pain Reliever');
insert into MEDICAMENTO (NOMBRE) values ('Thiola');
insert into MEDICAMENTO (NOMBRE) values ('Kadian');
insert into MEDICAMENTO (NOMBRE) values ('HYPERICUM PERFORATUM');
insert into MEDICAMENTO (NOMBRE) values ('Bupropion Hydrochloride (SR)');
insert into MEDICAMENTO (NOMBRE) values ('Cocculus Conium');
insert into MEDICAMENTO (NOMBRE) values ('LETROZOLE');
insert into MEDICAMENTO (NOMBRE) values ('Indomethacin');
insert into MEDICAMENTO (NOMBRE) values ('Risperidone');
insert into MEDICAMENTO (NOMBRE) values ('cool heat');
insert into MEDICAMENTO (NOMBRE) values ('Doxycycline');
insert into MEDICAMENTO (NOMBRE) values ('Donnatal');
insert into MEDICAMENTO (NOMBRE) values ('Isopropyl Alcohol');
insert into MEDICAMENTO (NOMBRE) values ('LBEL HYDRATESS');
insert into MEDICAMENTO (NOMBRE) values ('RECTICARE');
insert into MEDICAMENTO (NOMBRE) values ('Bupropion Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('eLenza Patch');
insert into MEDICAMENTO (NOMBRE) values ('Equisetum Formica');
insert into MEDICAMENTO (NOMBRE) values ('Ethereal Rose');
insert into MEDICAMENTO (NOMBRE) values ('Marcaine');
insert into MEDICAMENTO (NOMBRE) values ('Minocin');
insert into MEDICAMENTO (NOMBRE) values ('Oxygen Carbon Dioxide Mix');
insert into MEDICAMENTO (NOMBRE) values ('Meijer');
insert into MEDICAMENTO (NOMBRE) values ('Flucelvax');
insert into MEDICAMENTO (NOMBRE) values ('Wingscale');
insert into MEDICAMENTO (NOMBRE) values ('Ultravist');
insert into MEDICAMENTO (NOMBRE) values ('LIPIODOL');
insert into MEDICAMENTO (NOMBRE) values ('Torsemide');
insert into MEDICAMENTO (NOMBRE) values ('PEGINTRON');
insert into MEDICAMENTO (NOMBRE) values ('Metoprolol Tartrate and Hydrochlorothiazide');
insert into MEDICAMENTO (NOMBRE) values ('Antibacterial Wet Wipes');
insert into MEDICAMENTO (NOMBRE) values ('Zetonna');
insert into MEDICAMENTO (NOMBRE) values ('Mandarin Orange Antibacterial Hand');
insert into MEDICAMENTO (NOMBRE) values ('HOUSE DUST');
insert into MEDICAMENTO (NOMBRE) values ('ALOE VESTA SKIN CONDITIONER');
insert into MEDICAMENTO (NOMBRE) values ('ALLERGY');
insert into MEDICAMENTO (NOMBRE) values ('Theo-24');
insert into MEDICAMENTO (NOMBRE) values ('Skin-ion');
insert into MEDICAMENTO (NOMBRE) values ('IMAGE ESSENTIALS');
insert into MEDICAMENTO (NOMBRE) values ('Lisinopril');
insert into MEDICAMENTO (NOMBRE) values ('Leukine');
insert into MEDICAMENTO (NOMBRE) values ('Badger SPF 15 Sunscreen Lip Balm');
insert into MEDICAMENTO (NOMBRE) values ('Childrens Sabadil');
insert into MEDICAMENTO (NOMBRE) values ('Dexlido Kit');
insert into MEDICAMENTO (NOMBRE) values ('TERUFLEX Blood Bag System Anticoagulant Citrate Phosphate Dextrose Adenine (CPDA-1)');
insert into MEDICAMENTO (NOMBRE) values ('Gas Relief');
insert into MEDICAMENTO (NOMBRE) values ('Auro-Dri');
insert into MEDICAMENTO (NOMBRE) values ('Dandruff');
insert into MEDICAMENTO (NOMBRE) values ('Ocean Potion Quick Dry 30 Sunscreen');
insert into MEDICAMENTO (NOMBRE) values ('Nite Time Cold and Flu');
insert into MEDICAMENTO (NOMBRE) values ('Ipratropium bromide');
insert into MEDICAMENTO (NOMBRE) values ('CC Cream Medium');
insert into MEDICAMENTO (NOMBRE) values ('Fluvastatin');
insert into MEDICAMENTO (NOMBRE) values ('DOCTOR HOYS NATURAL PAIN RELIEF');
insert into MEDICAMENTO (NOMBRE) values ('Treatment Set TS329162');
insert into MEDICAMENTO (NOMBRE) values ('Calcium Gluconate');
insert into MEDICAMENTO (NOMBRE) values ('NATURAL LEMON MINT HERB THROAT DROPS');
insert into MEDICAMENTO (NOMBRE) values ('Midazolam Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Metronidazole');
insert into MEDICAMENTO (NOMBRE) values ('Milk of Magnesia');
insert into MEDICAMENTO (NOMBRE) values ('Methscopolamine Bromide');
insert into MEDICAMENTO (NOMBRE) values ('Quetiapine Fumarate');
insert into MEDICAMENTO (NOMBRE) values ('Black Oak');
insert into MEDICAMENTO (NOMBRE) values ('Tamsulosin Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('SudoGest');
insert into MEDICAMENTO (NOMBRE) values ('SHISEIDO RADIANT LIFTING FOUNDATION');
insert into MEDICAMENTO (NOMBRE) values ('Aspirin 81 mg');
insert into MEDICAMENTO (NOMBRE) values ('Tyzine');
insert into MEDICAMENTO (NOMBRE) values ('Atenolol');
insert into MEDICAMENTO (NOMBRE) values ('Pure Finish Mineral Powder Foundation SPF 20 Pure Finish 2');
insert into MEDICAMENTO (NOMBRE) values ('Golden Sunshine Herbal');
insert into MEDICAMENTO (NOMBRE) values ('Good Neighbor Pharmacy Nasal Decongestant');
insert into MEDICAMENTO (NOMBRE) values ('Gabapentin');
insert into MEDICAMENTO (NOMBRE) values ('DISCOUNT DRUG MART');
insert into MEDICAMENTO (NOMBRE) values ('Amazonian Colored Clay Foundation Broad Spectrum SPF 15 Sunscreen');
insert into MEDICAMENTO (NOMBRE) values ('Risperidone');
insert into MEDICAMENTO (NOMBRE) values ('Lisinopril');
insert into MEDICAMENTO (NOMBRE) values ('BOOST REGROWTH FOR WOMEN');
insert into MEDICAMENTO (NOMBRE) values ('Toviaz');
insert into MEDICAMENTO (NOMBRE) values ('Chantix');
insert into MEDICAMENTO (NOMBRE) values ('Paclitaxel');
insert into MEDICAMENTO (NOMBRE) values ('Delsym');
insert into MEDICAMENTO (NOMBRE) values ('Metolazone');
insert into MEDICAMENTO (NOMBRE) values ('Vichy Laboratoires LiftActiv Retinol HA');
insert into MEDICAMENTO (NOMBRE) values ('Simvastatin');
insert into MEDICAMENTO (NOMBRE) values ('Alendronate Sodium');
insert into MEDICAMENTO (NOMBRE) values ('Oxybutynin Chloride');
insert into MEDICAMENTO (NOMBRE) values ('Sheffield Baby Teething Gel');
insert into MEDICAMENTO (NOMBRE) values ('Softlips Coral Gloss');
insert into MEDICAMENTO (NOMBRE) values ('Methocarbamol');
insert into MEDICAMENTO (NOMBRE) values ('Naproxen Sodium');
insert into MEDICAMENTO (NOMBRE) values ('ALOE UP SUNSCREEN');
insert into MEDICAMENTO (NOMBRE) values ('Citanest Forte');
insert into MEDICAMENTO (NOMBRE) values ('good neighbor pharmacy cold');
insert into MEDICAMENTO (NOMBRE) values ('MEDITOWEL');
insert into MEDICAMENTO (NOMBRE) values ('Metoprolol Succinate');
insert into MEDICAMENTO (NOMBRE) values ('Benazepril Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('INDOCIN');
insert into MEDICAMENTO (NOMBRE) values ('EQUUS CABALLUS SKIN');
insert into MEDICAMENTO (NOMBRE) values ('Fentanyl');
insert into MEDICAMENTO (NOMBRE) values ('Glipizide');
insert into MEDICAMENTO (NOMBRE) values ('Phentermine Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('ziprasidone hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('GO TIME');
insert into MEDICAMENTO (NOMBRE) values ('Dimercaptosuccinic Acid');
insert into MEDICAMENTO (NOMBRE) values ('balance-n-brighten');
insert into MEDICAMENTO (NOMBRE) values ('Qualaquin');
insert into MEDICAMENTO (NOMBRE) values ('Amiloride Hydrochloride and Hydrochlorothiazide');
insert into MEDICAMENTO (NOMBRE) values ('Neutrogena SkinClearing');
insert into MEDICAMENTO (NOMBRE) values ('02 Balancing Foundation');
insert into MEDICAMENTO (NOMBRE) values ('Joint Pain');
insert into MEDICAMENTO (NOMBRE) values ('Propranolol Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Lansoprazole');
insert into MEDICAMENTO (NOMBRE) values ('care one fiber');
insert into MEDICAMENTO (NOMBRE) values ('SUPER ORIGIN COLLAGEN WATERPROOF BB');
insert into MEDICAMENTO (NOMBRE) values ('12 Male Reproductive');
insert into MEDICAMENTO (NOMBRE) values ('Pravastatin Sodium');
insert into MEDICAMENTO (NOMBRE) values ('Amoxicillin and Clavulanate Potassium');
insert into MEDICAMENTO (NOMBRE) values ('Stat-Foam');
insert into MEDICAMENTO (NOMBRE) values ('Bupropion Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Dr Bob Arnots Pain');
insert into MEDICAMENTO (NOMBRE) values ('ELOCON');
insert into MEDICAMENTO (NOMBRE) values ('STEMPHYLIUM SOLANI');
insert into MEDICAMENTO (NOMBRE) values ('NITROGEN');
insert into MEDICAMENTO (NOMBRE) values ('Alka-Seltzer Plus Cold Medicine Sparkling Original');
insert into MEDICAMENTO (NOMBRE) values ('MENHIBRIX');
insert into MEDICAMENTO (NOMBRE) values ('Diclofenac Potassium');
insert into MEDICAMENTO (NOMBRE) values ('Quetiapine fumarate');
insert into MEDICAMENTO (NOMBRE) values ('Pleo Mucedo');
insert into MEDICAMENTO (NOMBRE) values ('Wal Zyr');
insert into MEDICAMENTO (NOMBRE) values ('Clobetasol Propionate');
insert into MEDICAMENTO (NOMBRE) values ('IPKN Moist and Firm BB 02 MEDIUM');
insert into MEDICAMENTO (NOMBRE) values ('Hydrochlorothiazide');
insert into MEDICAMENTO (NOMBRE) values ('Dove Ultimate Go Fresh Burst');
insert into MEDICAMENTO (NOMBRE) values ('BZK');
insert into MEDICAMENTO (NOMBRE) values ('Ambien');
insert into MEDICAMENTO (NOMBRE) values ('Tobramycin');
insert into MEDICAMENTO (NOMBRE) values ('Clarithromycin');
insert into MEDICAMENTO (NOMBRE) values ('BICILLIN L-A');
insert into MEDICAMENTO (NOMBRE) values ('Critical Care Aspirin to Go');
insert into MEDICAMENTO (NOMBRE) values ('ANTI-AGING TINTED MOISTURIZER');
insert into MEDICAMENTO (NOMBRE) values ('Allerstat');
insert into MEDICAMENTO (NOMBRE) values ('ATORVASTATIN CALCIUM');
insert into MEDICAMENTO (NOMBRE) values ('Nighttime Sleep Aid');
insert into MEDICAMENTO (NOMBRE) values ('Amlodipine besylate');
insert into MEDICAMENTO (NOMBRE) values ('Fiore Rx Pixie Dust Pink Antifungal Nail Polish');
insert into MEDICAMENTO (NOMBRE) values ('Gadavist');
insert into MEDICAMENTO (NOMBRE) values ('Sunmark ibuprofen');
insert into MEDICAMENTO (NOMBRE) values ('Naproxen');
insert into MEDICAMENTO (NOMBRE) values ('Valium');
insert into MEDICAMENTO (NOMBRE) values ('CAREONE');
insert into MEDICAMENTO (NOMBRE) values ('Stomach Relief');
insert into MEDICAMENTO (NOMBRE) values ('Enalapril Maleate');
insert into MEDICAMENTO (NOMBRE) values ('Xopenex');
insert into MEDICAMENTO (NOMBRE) values ('Pantoprazole Sodium');
insert into MEDICAMENTO (NOMBRE) values ('O BlancTis');
insert into MEDICAMENTO (NOMBRE) values ('SF 5000 Plus');
insert into MEDICAMENTO (NOMBRE) values ('Lisinopril');
insert into MEDICAMENTO (NOMBRE) values ('Old Spice Red Zone Sweat Defense');
insert into MEDICAMENTO (NOMBRE) values ('Rheumatoid Arthritis Pain Management');
insert into MEDICAMENTO (NOMBRE) values ('Sertraline');
insert into MEDICAMENTO (NOMBRE) values ('Anacin');
insert into MEDICAMENTO (NOMBRE) values ('Lightning McQueen Sun Smacker SPF 24 Revved Up Raspberry');
insert into MEDICAMENTO (NOMBRE) values ('Gentamicin');
insert into MEDICAMENTO (NOMBRE) values ('Acarbose');
insert into MEDICAMENTO (NOMBRE) values ('TOPCARE');
insert into MEDICAMENTO (NOMBRE) values ('Pre-moistened Hemorrhoidal Pads');
insert into MEDICAMENTO (NOMBRE) values ('Acetaminophen And Codeine');
insert into MEDICAMENTO (NOMBRE) values ('Retin-A');
insert into MEDICAMENTO (NOMBRE) values ('ESIKA');
insert into MEDICAMENTO (NOMBRE) values ('Amitriptyline Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('allergy relief');
insert into MEDICAMENTO (NOMBRE) values ('Clonazepam');
insert into MEDICAMENTO (NOMBRE) values ('meloxicam');
insert into MEDICAMENTO (NOMBRE) values ('Acetaminophen');
insert into MEDICAMENTO (NOMBRE) values ('Cetirizine Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('topcare loperamide hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Gaboxetine');
insert into MEDICAMENTO (NOMBRE) values ('HYDREA');
insert into MEDICAMENTO (NOMBRE) values ('Acetaminophen and Codeine Phosphate');
insert into MEDICAMENTO (NOMBRE) values ('oxycodone hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('nausea relief');
insert into MEDICAMENTO (NOMBRE) values ('Potassium Chloride');
insert into MEDICAMENTO (NOMBRE) values ('Donepezil hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Sertraline');
insert into MEDICAMENTO (NOMBRE) values ('Gadavyt Cough');
insert into MEDICAMENTO (NOMBRE) values ('Clonidine Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('equate ibuprofen');
insert into MEDICAMENTO (NOMBRE) values ('Cocculus Indicus Kit Refill');
insert into MEDICAMENTO (NOMBRE) values ('Hydroxyzine Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Maybelline New York Baby Lips Dr Rescue Medicated Balm');
insert into MEDICAMENTO (NOMBRE) values ('Simvastatin');
insert into MEDICAMENTO (NOMBRE) values ('Gentamicin Sulfate');
insert into MEDICAMENTO (NOMBRE) values ('Ofloxacin Ophthalmic');
insert into MEDICAMENTO (NOMBRE) values ('AK-POLY-BAC');
insert into MEDICAMENTO (NOMBRE) values ('Bromday');
insert into MEDICAMENTO (NOMBRE) values ('Food - Plant Source, Orange Citrus sinensis');
insert into MEDICAMENTO (NOMBRE) values ('Morning Fresh');
insert into MEDICAMENTO (NOMBRE) values ('Penicillin V Potassium');
insert into MEDICAMENTO (NOMBRE) values ('Menstrual Relief');
insert into MEDICAMENTO (NOMBRE) values ('Amlodipine Besylate');
insert into MEDICAMENTO (NOMBRE) values ('Hand Sanitizer');
insert into MEDICAMENTO (NOMBRE) values ('Medi-First Sterile Alcohol Pads');
insert into MEDICAMENTO (NOMBRE) values ('Sniffly Sprinkles');
insert into MEDICAMENTO (NOMBRE) values ('KETOROLAC TROMETHAMINE');
insert into MEDICAMENTO (NOMBRE) values ('Meclizine Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Correway Sunscreen (Non-waterproof)');
insert into MEDICAMENTO (NOMBRE) values ('Q Tapp Cold and Cough');
insert into MEDICAMENTO (NOMBRE) values ('Lovastatin');
insert into MEDICAMENTO (NOMBRE) values ('Pravastatin Sodium');
insert into MEDICAMENTO (NOMBRE) values ('bareMinerals bareSkin Pure Brightening Serum Foundation Broad Spectrum SPF 20');
insert into MEDICAMENTO (NOMBRE) values ('PAROXETINE');
insert into MEDICAMENTO (NOMBRE) values ('Acetaminophen PM');
insert into MEDICAMENTO (NOMBRE) values ('Cold Spot');
insert into MEDICAMENTO (NOMBRE) values ('Lidocaine');
insert into MEDICAMENTO (NOMBRE) values ('Edluar');
insert into MEDICAMENTO (NOMBRE) values ('Clonidine Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('EROS BODYGLIDE');
insert into MEDICAMENTO (NOMBRE) values ('laura mercier Tinted Moisturizer Creme Compact Broad Spectrum SPF 20 Sunscreen FAWN');
insert into MEDICAMENTO (NOMBRE) values ('Abridge Cold Sore Treatment');
insert into MEDICAMENTO (NOMBRE) values ('Pure petroleum');
insert into MEDICAMENTO (NOMBRE) values ('Lidocaine Hydrochloride and Epinephrine');
insert into MEDICAMENTO (NOMBRE) values ('Cow Milk');
insert into MEDICAMENTO (NOMBRE) values ('Terrasil Shingles Treatment');
insert into MEDICAMENTO (NOMBRE) values ('WEGMANS');
insert into MEDICAMENTO (NOMBRE) values ('INSTANT HAND SANITIZER WITH ALOE and VITAMIN E');
insert into MEDICAMENTO (NOMBRE) values ('INSOMNIA');
insert into MEDICAMENTO (NOMBRE) values ('Teething Complex');
insert into MEDICAMENTO (NOMBRE) values ('SENSODYNE');
insert into MEDICAMENTO (NOMBRE) values ('ChapStick Classic Spearmint');
insert into MEDICAMENTO (NOMBRE) values ('SHISEIDO SHEER MATIFYING COMPACT (REFILL)');
insert into MEDICAMENTO (NOMBRE) values ('Old Spice');
insert into MEDICAMENTO (NOMBRE) values ('sunmark');
insert into MEDICAMENTO (NOMBRE) values ('ZOLPIDEM TARTRATE');
insert into MEDICAMENTO (NOMBRE) values ('Fresh Sugar Plum Tinted Lip Treatment SPF 15');
insert into MEDICAMENTO (NOMBRE) values ('Omeprazole Magnesium');
insert into MEDICAMENTO (NOMBRE) values ('Quinapril Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('HEMATOGEN');
insert into MEDICAMENTO (NOMBRE) values ('Dicyclomine Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Piroxicam');
insert into MEDICAMENTO (NOMBRE) values ('Naproxen');
insert into MEDICAMENTO (NOMBRE) values ('NEUTRAMAXX 5000 TCP');
insert into MEDICAMENTO (NOMBRE) values ('TRAMADOL HYDROCHLORIDE');
insert into MEDICAMENTO (NOMBRE) values ('FLAWLESS FINISH PERFECTLY NUDE MAKEUP BROAD SPECTRUM SUNSCREEN SPF 15 SHADE ALABASTER');
insert into MEDICAMENTO (NOMBRE) values ('Benztropine Mesylate');
insert into MEDICAMENTO (NOMBRE) values ('Pollens - Grasses, Brome, Smooth Bromus inermis');
insert into MEDICAMENTO (NOMBRE) values ('care one pain relief');
insert into MEDICAMENTO (NOMBRE) values ('Warfarin Sodium');
insert into MEDICAMENTO (NOMBRE) values ('Furosemide');
insert into MEDICAMENTO (NOMBRE) values ('Heartburn');
insert into MEDICAMENTO (NOMBRE) values ('Stool Softener');
insert into MEDICAMENTO (NOMBRE) values ('PerioMed');
insert into MEDICAMENTO (NOMBRE) values ('Methscopolamine Bromide');
insert into MEDICAMENTO (NOMBRE) values ('Furosemide');
insert into MEDICAMENTO (NOMBRE) values ('Escitalopram');
insert into MEDICAMENTO (NOMBRE) values ('TRAMADOL HYDROCHLORIDE');
insert into MEDICAMENTO (NOMBRE) values ('Metformin hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Ibuprofen');
insert into MEDICAMENTO (NOMBRE) values ('Acetaminophen');
insert into MEDICAMENTO (NOMBRE) values ('Trifluoperazine Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Mineral Oil');
insert into MEDICAMENTO (NOMBRE) values ('LEVOTHYROXINE');
insert into MEDICAMENTO (NOMBRE) values ('MIRTAZAPINE');
insert into MEDICAMENTO (NOMBRE) values ('American Red Cross First Aid Kit');
insert into MEDICAMENTO (NOMBRE) values ('Cleocin Phosphate');
insert into MEDICAMENTO (NOMBRE) values ('Badger SPF 34 Anti-Bug Sunscreen');
insert into MEDICAMENTO (NOMBRE) values ('Cover Fx Blemish Treatment Concealer N Deep');
insert into MEDICAMENTO (NOMBRE) values ('GOLDEN BALL HEALER');
insert into MEDICAMENTO (NOMBRE) values ('Lactovit Mens Roll-On Antiperspirant Deodorant');
insert into MEDICAMENTO (NOMBRE) values ('Yellow Onion');
insert into MEDICAMENTO (NOMBRE) values ('Duck Feathers');
insert into MEDICAMENTO (NOMBRE) values ('valacyclovir hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Gabapentin');
insert into MEDICAMENTO (NOMBRE) values ('Lisinopril and Hydrochlorothiazide');
insert into MEDICAMENTO (NOMBRE) values ('HGH Plus');
insert into MEDICAMENTO (NOMBRE) values ('GAMMAGARD');
insert into MEDICAMENTO (NOMBRE) values ('Pyridostigmine Bromide');
insert into MEDICAMENTO (NOMBRE) values ('Lidocaine Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Diphenhydramine Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('ALLERGY');
insert into MEDICAMENTO (NOMBRE) values ('Sisal');
insert into MEDICAMENTO (NOMBRE) values ('CLINIMIX');
insert into MEDICAMENTO (NOMBRE) values ('Mobic');
insert into MEDICAMENTO (NOMBRE) values ('Phendimetrazine Tartrate');
insert into MEDICAMENTO (NOMBRE) values ('Lovastatin');
insert into MEDICAMENTO (NOMBRE) values ('Pantoprazole Sodium');
insert into MEDICAMENTO (NOMBRE) values ('Pentazocine HCl and Acetaminophen');
insert into MEDICAMENTO (NOMBRE) values ('Quetiapine fumarate');
insert into MEDICAMENTO (NOMBRE) values ('Propranolol Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('ropinirole');
insert into MEDICAMENTO (NOMBRE) values ('Venlafaxine Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Bactestat');
insert into MEDICAMENTO (NOMBRE) values ('AVOCADO');
insert into MEDICAMENTO (NOMBRE) values ('ATACAND');
insert into MEDICAMENTO (NOMBRE) values ('Nan San MUSFLEX External Analgesic');
insert into MEDICAMENTO (NOMBRE) values ('Muscular Pain Relief');
insert into MEDICAMENTO (NOMBRE) values ('Ropinirole');
insert into MEDICAMENTO (NOMBRE) values ('Zyprexa');
insert into MEDICAMENTO (NOMBRE) values ('Estazolam');
insert into MEDICAMENTO (NOMBRE) values ('Magnesium Sulfate');
insert into MEDICAMENTO (NOMBRE) values ('Speed Stick');
insert into MEDICAMENTO (NOMBRE) values ('PULMICORT RESPULES');
insert into MEDICAMENTO (NOMBRE) values ('Indomethacin');
insert into MEDICAMENTO (NOMBRE) values ('family wellness hemorrhoidal');
insert into MEDICAMENTO (NOMBRE) values ('Butalbital, Acetaminophen and Caffeine');
insert into MEDICAMENTO (NOMBRE) values ('Etodolac');
insert into MEDICAMENTO (NOMBRE) values ('Topcare Cold and Sore Throat');
insert into MEDICAMENTO (NOMBRE) values ('Tuna');
insert into MEDICAMENTO (NOMBRE) values ('TARSUM PROFESSIONAL');
insert into MEDICAMENTO (NOMBRE) values ('EQUATE');
insert into MEDICAMENTO (NOMBRE) values ('HYSAN PAIN RELIEVER');
insert into MEDICAMENTO (NOMBRE) values ('Sore Throat Logenzes');
insert into MEDICAMENTO (NOMBRE) values ('Neutrogena Healthy Skin Compact Makeup');
insert into MEDICAMENTO (NOMBRE) values ('Neutrogena Body Clear Body Scrub');
insert into MEDICAMENTO (NOMBRE) values ('Cyanocobalamin');
insert into MEDICAMENTO (NOMBRE) values ('OXY Daily Moisturizer');
insert into MEDICAMENTO (NOMBRE) values ('Ondansetron');
insert into MEDICAMENTO (NOMBRE) values ('JAFRA PRO FACE LIFT');
insert into MEDICAMENTO (NOMBRE) values ('zinc oxide');
insert into MEDICAMENTO (NOMBRE) values ('Hemorrhoids Relief');
insert into MEDICAMENTO (NOMBRE) values ('Dermisa');
insert into MEDICAMENTO (NOMBRE) values ('Midazolam HCl');
insert into MEDICAMENTO (NOMBRE) values ('Clotrimazole');
insert into MEDICAMENTO (NOMBRE) values ('Hydrogen Peroxide');
insert into MEDICAMENTO (NOMBRE) values ('Simvastatin');
insert into MEDICAMENTO (NOMBRE) values ('Hypochondria');
insert into MEDICAMENTO (NOMBRE) values ('OPANA');
insert into MEDICAMENTO (NOMBRE) values ('Diltiazem Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('SHISEIDO');
insert into MEDICAMENTO (NOMBRE) values ('Fresh Sugar Passion Tinted Lip Treatment SPF 15');
insert into MEDICAMENTO (NOMBRE) values ('Turnip');
insert into MEDICAMENTO (NOMBRE) values ('GODDESS GARDEN ORGANICS Sunny Face NATURAL SUNSCREEN BROAD SPECTRUM SPF 30 WATER RESISTANT');
insert into MEDICAMENTO (NOMBRE) values ('SUPER CITY BLOCK');
insert into MEDICAMENTO (NOMBRE) values ('Ondansetron');
insert into MEDICAMENTO (NOMBRE) values ('Vaniply');
insert into MEDICAMENTO (NOMBRE) values ('Metformin hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('DESPEC');
insert into MEDICAMENTO (NOMBRE) values ('Quit Nits Advance');
insert into MEDICAMENTO (NOMBRE) values ('Yes To Grapefruit Moisturizer with SPF15');
insert into MEDICAMENTO (NOMBRE) values ('Shrimp');
insert into MEDICAMENTO (NOMBRE) values ('Duck Feathers');
insert into MEDICAMENTO (NOMBRE) values ('Daily Body Moisture Hydrating Complex SPF8');
insert into MEDICAMENTO (NOMBRE) values ('Fentanyl');
insert into MEDICAMENTO (NOMBRE) values ('TRAMADOL HYDROCHLORIDE');
insert into MEDICAMENTO (NOMBRE) values ('Sodium Chloride');
insert into MEDICAMENTO (NOMBRE) values ('Saline Nasal');
insert into MEDICAMENTO (NOMBRE) values ('Clonidine Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Leader ClearLax');
insert into MEDICAMENTO (NOMBRE) values ('Bupropion Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Sun Shades Lip Balm');
insert into MEDICAMENTO (NOMBRE) values ('Atenolol');
insert into MEDICAMENTO (NOMBRE) values ('CLE DE PEAU BEAUTE CR COMPACT FOUNDATION');
insert into MEDICAMENTO (NOMBRE) values ('Captopril');
insert into MEDICAMENTO (NOMBRE) values ('Mirtazapine');
insert into MEDICAMENTO (NOMBRE) values ('Nicorette');
insert into MEDICAMENTO (NOMBRE) values ('Cialis');
insert into MEDICAMENTO (NOMBRE) values ('Gabapentin');
insert into MEDICAMENTO (NOMBRE) values ('Citalopram');
insert into MEDICAMENTO (NOMBRE) values ('Timolol Maleate');
insert into MEDICAMENTO (NOMBRE) values ('Mango Blossom');
insert into MEDICAMENTO (NOMBRE) values ('anti-bacterial foaming');
insert into MEDICAMENTO (NOMBRE) values ('StarCap Medical Private Limited');
insert into MEDICAMENTO (NOMBRE) values ('Joy');
insert into MEDICAMENTO (NOMBRE) values ('Oxygen');
insert into MEDICAMENTO (NOMBRE) values ('Probenecid');
insert into MEDICAMENTO (NOMBRE) values ('MakeSense');
insert into MEDICAMENTO (NOMBRE) values ('Homeopathic Hangover Formula');
insert into MEDICAMENTO (NOMBRE) values ('Isopropyl Alcohol');
insert into MEDICAMENTO (NOMBRE) values ('Sleep RELIEF');
insert into MEDICAMENTO (NOMBRE) values ('ClomiPHENE Citrate');
insert into MEDICAMENTO (NOMBRE) values ('A.H.C Real Eye For Face');
insert into MEDICAMENTO (NOMBRE) values ('TYSABRI');
insert into MEDICAMENTO (NOMBRE) values ('Lorazepam');
insert into MEDICAMENTO (NOMBRE) values ('smart sense sinus');
insert into MEDICAMENTO (NOMBRE) values ('Foot Works Healthy');
insert into MEDICAMENTO (NOMBRE) values ('Sulfamethoxazole and Trimethoprim');
insert into MEDICAMENTO (NOMBRE) values ('DermaCen Foaming Antimicrobial-T Hand');
insert into MEDICAMENTO (NOMBRE) values ('antacid');
insert into MEDICAMENTO (NOMBRE) values ('Osteodoron AM Bone Support');
insert into MEDICAMENTO (NOMBRE) values ('Harmon Face Values');
insert into MEDICAMENTO (NOMBRE) values ('SORGHUM HALEPENSE POLLEN');
insert into MEDICAMENTO (NOMBRE) values ('Childrens Allergy Relief');
insert into MEDICAMENTO (NOMBRE) values ('RITE AID RENEWAL');
insert into MEDICAMENTO (NOMBRE) values ('Isosorbide Dinitrate');
insert into MEDICAMENTO (NOMBRE) values ('Doxycycline');
insert into MEDICAMENTO (NOMBRE) values ('Mineral Wear Talc-Free Mineral Face Powder');
insert into MEDICAMENTO (NOMBRE) values ('WHITE GRAY BIRCH POLLEN');
insert into MEDICAMENTO (NOMBRE) values ('Topiramate');
insert into MEDICAMENTO (NOMBRE) values ('Stress');
insert into MEDICAMENTO (NOMBRE) values ('Felodipine');
insert into MEDICAMENTO (NOMBRE) values ('mally Lip Defender');
insert into MEDICAMENTO (NOMBRE) values ('Mountain Series Weekender Medical');
insert into MEDICAMENTO (NOMBRE) values ('Bamboo Rosemary');
insert into MEDICAMENTO (NOMBRE) values ('ziprasidone hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Sufentanil Citrate');
insert into MEDICAMENTO (NOMBRE) values ('Sure Comfort Alcohol Prep Pads');
insert into MEDICAMENTO (NOMBRE) values ('ADVAIR');
insert into MEDICAMENTO (NOMBRE) values ('NAUSEA');
insert into MEDICAMENTO (NOMBRE) values ('Naproxen Sodium');
insert into MEDICAMENTO (NOMBRE) values ('Asthma');
insert into MEDICAMENTO (NOMBRE) values ('Ziprasidone hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Thallous Chloride Tl 201');
insert into MEDICAMENTO (NOMBRE) values ('Allergy HP');
insert into MEDICAMENTO (NOMBRE) values ('Colds Dry Cough');
insert into MEDICAMENTO (NOMBRE) values ('Medroxyprogesterone Acetate');
insert into MEDICAMENTO (NOMBRE) values ('Clindamycin hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('NeoStrata Sheer Hydration');
insert into MEDICAMENTO (NOMBRE) values ('Remedy Phytoplex Z-Guard');
insert into MEDICAMENTO (NOMBRE) values ('Hog Epithelium');
insert into MEDICAMENTO (NOMBRE) values ('Biovi Total Beauty');
insert into MEDICAMENTO (NOMBRE) values ('Viagra');
insert into MEDICAMENTO (NOMBRE) values ('Cefadroxil');
insert into MEDICAMENTO (NOMBRE) values ('Hand Sanitizer');
insert into MEDICAMENTO (NOMBRE) values ('Alprazolam');
insert into MEDICAMENTO (NOMBRE) values ('Fludarabine Phosphate');
insert into MEDICAMENTO (NOMBRE) values ('Lithium Carbonate');
insert into MEDICAMENTO (NOMBRE) values ('PROVENCE MELTING FOUNDATION');
insert into MEDICAMENTO (NOMBRE) values ('Isopropyl alcohol Swabstick Sterile');
insert into MEDICAMENTO (NOMBRE) values ('Bupropion Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Diaper Rash');
insert into MEDICAMENTO (NOMBRE) values ('Standardized Grass Pollen, Grass Mix 5');
insert into MEDICAMENTO (NOMBRE) values ('Ibuprofen');
insert into MEDICAMENTO (NOMBRE) values ('Gabapentin');
insert into MEDICAMENTO (NOMBRE) values ('Flucytosine');
insert into MEDICAMENTO (NOMBRE) values ('Acne');
insert into MEDICAMENTO (NOMBRE) values ('PURELL Instant Hand Sanitizer Foam (ETHYL ALCOHOL)');
insert into MEDICAMENTO (NOMBRE) values ('RIBASPHERE RibaPak');
insert into MEDICAMENTO (NOMBRE) values ('Ponstel');
insert into MEDICAMENTO (NOMBRE) values ('ENC');
insert into MEDICAMENTO (NOMBRE) values ('Warfarin Sodium');
insert into MEDICAMENTO (NOMBRE) values ('Equate omeprazole delayed release');
insert into MEDICAMENTO (NOMBRE) values ('Hesol Rim');
insert into MEDICAMENTO (NOMBRE) values ('Oral Soothe');
insert into MEDICAMENTO (NOMBRE) values ('Stress Control');
insert into MEDICAMENTO (NOMBRE) values ('Pollens - Trees, Oak Mix');
insert into MEDICAMENTO (NOMBRE) values ('bethanechol chloride');
insert into MEDICAMENTO (NOMBRE) values ('METHOTREXATE');
insert into MEDICAMENTO (NOMBRE) values ('DELFLEX');
insert into MEDICAMENTO (NOMBRE) values ('Humalog');
insert into MEDICAMENTO (NOMBRE) values ('Lisinopril');
insert into MEDICAMENTO (NOMBRE) values ('Terbinafine Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('TOMATO');
insert into MEDICAMENTO (NOMBRE) values ('Terrasil Skin Repair');
insert into MEDICAMENTO (NOMBRE) values ('Pistachio');
insert into MEDICAMENTO (NOMBRE) values ('Ramipril');
insert into MEDICAMENTO (NOMBRE) values ('shoprite acetaminophen');
insert into MEDICAMENTO (NOMBRE) values ('PEG-3350, sodium chloride, sodium bicarbonate and potassium chloride');
insert into MEDICAMENTO (NOMBRE) values ('Sambucol Cold and Flu Night Time Syrup');
insert into MEDICAMENTO (NOMBRE) values ('Triamcinolone Acetonide');
insert into MEDICAMENTO (NOMBRE) values ('AMARANTHUS TUBERCULATUS POLLEN');
insert into MEDICAMENTO (NOMBRE) values ('PAROXETINE');
insert into MEDICAMENTO (NOMBRE) values ('Lymphonest');
insert into MEDICAMENTO (NOMBRE) values ('ABILIFY');
insert into MEDICAMENTO (NOMBRE) values ('IMURAN');
insert into MEDICAMENTO (NOMBRE) values ('Clarithromycin');
insert into MEDICAMENTO (NOMBRE) values ('MOMETASONE FUROATE');
insert into MEDICAMENTO (NOMBRE) values ('Pravastatin Sodium');
insert into MEDICAMENTO (NOMBRE) values ('MEBENDAZOLE');
insert into MEDICAMENTO (NOMBRE) values ('QUERCUS AGRIFOLIA POLLEN');
insert into MEDICAMENTO (NOMBRE) values ('Aluminum Hydroxide');
insert into MEDICAMENTO (NOMBRE) values ('Hydroxyzine Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('Peanut');
insert into MEDICAMENTO (NOMBRE) values ('Rescue Sleep');
insert into MEDICAMENTO (NOMBRE) values ('CABBAGE');
insert into MEDICAMENTO (NOMBRE) values ('Tomato Day Broad Spectrum SPF 16 Sunscreen');
insert into MEDICAMENTO (NOMBRE) values ('CareOne Daily Moisturizer Broad Spectrum SPF15 Sunscreen');
insert into MEDICAMENTO (NOMBRE) values ('Lucky Instant Hand Sanitizer with Aloe Vera');
insert into MEDICAMENTO (NOMBRE) values ('CLINIMIX');
insert into MEDICAMENTO (NOMBRE) values ('Levetiracetam');
insert into MEDICAMENTO (NOMBRE) values ('Gabapentin');
insert into MEDICAMENTO (NOMBRE) values ('DulcoEase Pink');
insert into MEDICAMENTO (NOMBRE) values ('Old Spice High Endurance');
insert into MEDICAMENTO (NOMBRE) values ('CYCLOBENZAPRINE HYROCHLORIDE');
insert into MEDICAMENTO (NOMBRE) values ('Oxcarbazepine');
insert into MEDICAMENTO (NOMBRE) values ('Fexofenadine Hydrochloride');
insert into MEDICAMENTO (NOMBRE) values ('FEXOFENADINE HYDROCHLORIDE');
insert into MEDICAMENTO (NOMBRE) values ('Rhus Aconitum');
insert into MEDICAMENTO (NOMBRE) values ('GUNA-IL 6');
insert into MEDICAMENTO (NOMBRE) values ('Mucinex');
insert into MEDICAMENTO (NOMBRE) values ('WHITE FLOWER STRAIN RELIEF');
insert into MEDICAMENTO (NOMBRE) values ('Arnica Aurum 20/30');
