/*TEST TRIGGERS*/

SELECT * FROM USUARIO WHERE NICK = 'USUARIOPRUEBA'
GO

SELECT * FROM CICLOMENSTRUAL WHERE ID_USUARIO = 'USUARIOPRUEBA'

GO
SELECT * FROM EMBARAZO WHERE ID_USUARIO = 'USUARIOPRUEBA'
GO

SELECT * FROM REVISIONMEDICA WHERE ID_EMBARAZO IN (SELECT ID FROM EMBARAZO WHERE ID_USUARIO = 'USUARIOPRUEBA')

GO
SELECT * FROM REVISIONPERSONAL WHERE ID_USUARIO = 'USUARIOPRUEBA'
GO
DELETE FROM EMBARAZO WHERE FECHAFIN_REAL IS NULL AND ID_USUARIO = 'USUARIOPRUEBA'
GO
DELETE FROM CICLOMENSTRUAL WHERE FECHAFIN_REAL IS NULL AND ID_USUARIO = 'USUARIOPRUEBA'


/*PRUEBA TESTS FECHAS SUPERPUESTAS*/
--PRIMERO BORRAMOS TODOS LOS CICLOS DEL USUARIO DE PRUEBA
DELETE FROM EMBARAZO WHERE ID_USUARIO = 'USUARIOPRUEBA'
GO
DELETE FROM CICLOMENSTRUAL WHERE ID_USUARIO = 'USUARIOPRUEBA'

--COMPROBAMOS QUE ESTAN BORRADOS
SELECT * FROM CICLOMENSTRUAL WHERE ID_USUARIO = 'USUARIOPRUEBA'

GO
SELECT * FROM EMBARAZO WHERE ID_USUARIO = 'USUARIOPRUEBA'

--CREAMOS UN CICLO MENSTRUAL CON FECHA DE INICIO Y DE FIN 
INSERT INTO CICLOMENSTRUAL (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
VALUES('USUARIOPRUEBA', '20180601','20180605')	--EL CICLO DURA DEL 01/06/2018 AL 05/06/2018

--AHORA PRUEBAS QUE DEBEN FALLAR:
		--INSERTAR UN CICLO MENSTRUAL DENTRO DEL PERIODO DEL CICLO MENSTRUAL ANTERIOR
			INSERT INTO CICLOMENSTRUAL (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180602','20180604')	--DEL 02/06/2018 AL 04/06/2018
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'Ya existe un ciclo menstrual en esa fecha'

		--INSERTAR UN CICLO MENSTRUAL CUYA FECHA DE FIN INVADA LA FECHA DE INICIO DEL CICLO MENSTRUAL ANTERIOR
			INSERT INTO CICLOMENSTRUAL (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180602',NULL)	--DEL 02/06/2018 A SIN FECHA DE CIERRE
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'Ya existe un ciclo menstrual en esa fecha'

		--INSERTAR UN CICLO MENSTRUAL CUYA FECHA DE FIN INVADA LA FECHA DE INICIO DEL CICLO MENSTRUAL ANTERIOR Y LA FECHA DE FIN SOBREPASE LA
			--FECHA DE FIN DEL CICLO ANTERIOR
			INSERT INTO CICLOMENSTRUAL (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180602','20180615')	--DEL 02/06/2018 A 15/06/2018
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'Ya existe un ciclo menstrual en esa fecha'
		
		--INSERTAR UN CICLO MENSTRUAL CUYA FECHA DE INICIO INVADA LA FECHA DE FIN DEL CICLO MENSTRUAL ANTERIOR 
			INSERT INTO CICLOMENSTRUAL (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180604','20180615')	--DEL 04/06/2018 A 15/06/2018
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'Ya existe un ciclo menstrual en esa fecha'
		
		--INSERTAR UN CICLO MENSTRUAL CUYA DURACION INCLUYA EL PERIODO DEL CICLO ANTERIOR
			INSERT INTO CICLOMENSTRUAL (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180504','20180615')	--DEL 04/05/2018 A 15/06/2018
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'Ya existe un ciclo menstrual en esa fecha'

--PRUEBA QUE NO DEBE FALLAR:
		--INSERTAR UN CICLO MENSTRUAL ANTES DEL CICLO MENSTRUAL ANTERIOR
			INSERT INTO CICLOMENSTRUAL (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180504','20180507')	--DEL 04/05/2018 A 07/05/2018
		--INSERTAR UN CICLO MENSTRUAL DESPUES DEL CICLO MENSTRUAL ANTERIOR
			INSERT INTO CICLOMENSTRUAL (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180704','20180707')	--DEL 04/07/2018 A 07/07/2018


--PRUEBAS QUE DEBEN FALLAR ESTA VEZ AÑADIENDO UN EMBARAZO (EXISTIENDO YA UN CICLO MENSTRUAL)
--AHORA PRUEBAS QUE DEBEN FALLAR:
		--INSERTAR UN EMBARAZO DENTRO DEL PERIODO DEL CICLO MENSTRUAL ANTERIOR
			INSERT INTO EMBARAZO(ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180602','20180604')	--DEL 02/06/2018 AL 04/06/2018
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'No se puede insertar un embarazo en mitad de un ciclo'

		--INSERTAR UN EMBARAZO CUYA FECHA DE FIN INVADA LA FECHA DE INICIO DEL CICLO MENSTRUAL ANTERIOR
			INSERT INTO EMBARAZO (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180602',NULL)	--DEL 02/06/2018 A SIN FECHA DE CIERRE
				
				---EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'No se puede insertar un embarazo en mitad de un ciclo'

		--INSERTAR UN EMBARAZO CUYA FECHA DE FIN INVADA LA FECHA DE INICIO DEL CICLO MENSTRUAL ANTERIOR Y LA FECHA DE FIN SOBREPASE LA
			--FECHA DE FIN DEL CICLO ANTERIOR
			INSERT INTO EMBARAZO (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180602','20180615')	--DEL 02/06/2018 A 15/06/2018
				
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'No se puede insertar un embarazo en mitad de un ciclo'
		
		--INSERTAR UN EMBARAZO CUYA FECHA DE INICIO INVADA LA FECHA DE FIN DEL CICLO MENSTRUAL ANTERIOR 
			INSERT INTO EMBARAZO (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180604','20180615')	--DEL 04/06/2018 A 15/06/2018
				---EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'No se puede insertar un embarazo en mitad de un ciclo'
		
		--INSERTAR UN EMBARAZO CUYA DURACION INCLUYA EL PERIODO DEL CICLO ANTERIOR
			INSERT INTO EMBARAZO (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180604','20180615')	--DEL 01/05/2018 A 15/06/2018
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'No se puede insertar un embarazo en mitad de un ciclo'

			

--PRUEBA QUE NO DEBE FALLAR:
--BORRAMOS LOS DATOS ANTERIORES
		--INSERTAR UN EMBARAZO ANTES DEL CICLO MENSTRUAL ANTERIOR
			INSERT INTO EMBARAZO(ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180504','20180507')	--DEL 04/05/2018 A 07/05/2018
		--INSERTAR UN EMBARAZO DESPUES DEL CICLO MENSTRUAL ANTERIOR
			INSERT INTO EMBARAZO(ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180704','20180707')	--DEL 04/07/2018 A 07/07/2018

			------------------------------------------------------------------------------------------------------
						
			
--AHORA VOLVEMOS A BORRAR TODO DEL USUARIO

--PRIMERO BORRAMOS TODOS LOS CICLOS DEL USUARIO DE PRUEBA
DELETE FROM EMBARAZO WHERE ID_USUARIO = 'USUARIOPRUEBA'
GO
DELETE FROM CICLOMENSTRUAL WHERE ID_USUARIO = 'USUARIOPRUEBA'

--COMPROBAMOS QUE ESTAN BORRADOS
SELECT * FROM CICLOMENSTRUAL WHERE ID_USUARIO = 'USUARIOPRUEBA'

GO
SELECT * FROM EMBARAZO WHERE ID_USUARIO = 'USUARIOPRUEBA'

--CREAMOS UN EMBARAZO CON FECHA DE INICIO Y DE FIN 
INSERT INTO EMBARAZO(ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
VALUES('USUARIOPRUEBA', '20180601','20180605')	--EL CICLO DURA DEL 01/06/2018 AL 05/06/2018


--AHORA PRUEBAS QUE DEBEN FALLAR:
		--INSERTAR UN EMBARAZO DENTRO DEL PERIODO DEL EMBARAZO ANTERIOR
			INSERT INTO EMBARAZO (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180602','20180604')	--DEL 02/06/2018 AL 04/06/2018
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'Ya existe un embarazo en esa fecha'

		--INSERTAR UN EMBARAZO CUYA FECHA DE FIN INVADA LA FECHA DE INICIO DEL EMBARAZO ANTERIOR
			INSERT INTO EMBARAZO (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180602',NULL)	--DEL 02/06/2018 A SIN FECHA DE CIERRE
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'Ya existe un embarazo en esa fecha'

		--INSERTAR UN EMBARAZO CUYA FECHA DE FIN INVADA LA FECHA DE INICIO DEL EMBARAZO ANTERIOR Y LA FECHA DE FIN SOBREPASE LA
			--FECHA DE FIN DEL EMBARAZO ANTERIOR
			INSERT INTO EMBARAZO (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180602','20180615')	--DEL 02/06/2018 A 15/06/2018
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'Ya existe un embarazo en esa fecha'
		
		--INSERTAR UN EMBARAZO CUYA FECHA DE INICIO INVADA LA FECHA DE FIN DEL EMBARAZO ANTERIOR 
			INSERT INTO EMBARAZO (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180604','20180615')	--DEL 04/06/2018 A 15/06/2018
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'Ya existe un embarazo en esa fecha'
		
		--INSERTAR UN EMBARAZOL CUYA DURACION INCLUYA EL PERIODO DEL EMBARAZO ANTERIOR
			INSERT INTO EMBARAZO (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180604','20180615')	--DEL 01/05/2018 A 15/06/2018
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'Ya existe un embarazo en esa fecha'

--PRUEBA QUE NO DEBE FALLAR:
--BORRAMOS LOS DATOS ANTERIORES
		--INSERTAR UN EMBARAZO ANTES DEL EMBARAZO ANTERIOR
			INSERT INTO EMBARAZO(ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180504','20180507')	--DEL 04/05/2018 A 07/05/2018
		--INSERTAR UN EMBARAZO DESPUES DEL EMBARAZO ANTERIOR
			INSERT INTO EMBARAZO(ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180704','20180707')	--DEL 04/07/2018 A 07/07/2018


--PRUEBAS QUE DEBEN FALLAR ESTA VEZ AÑADIENDO UN CICLOMENSTRUAL (EXISTIENDO YA UN EMBARAZO)
--AHORA PRUEBAS QUE DEBEN FALLAR:
		--INSERTAR UN CICLO MENSTRUAL DENTRO DEL PERIODO DEL EMBARAZO ANTERIOR
			INSERT INTO CICLOMENSTRUAL(ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180602','20180604')	--DEL 02/06/2018 AL 04/06/2018
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'No se puede insertar una menstruacion en mitad de un embarazo'

		--INSERTAR UN CICLO MENSTRUAL CUYA FECHA DE FIN INVADA LA FECHA DE INICIO DEL EMBARAZO ANTERIOR
			INSERT INTO CICLOMENSTRUAL (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180602',NULL)	--DEL 02/06/2018 A SIN FECHA DE CIERRE
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'No se puede insertar una menstruacion en mitad de un embarazo'

		--INSERTAR UN CICLO MENSTRUAL CUYA FECHA DE FIN INVADA LA FECHA DE INICIO DEL CICLO MENSTRUAL ANTERIOR Y LA FECHA DE FIN SOBREPASE LA
			--FECHA DE FIN DEL EMBARAZO ANTERIOR
			INSERT INTO CICLOMENSTRUAL (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180602','20180615')	--DEL 02/06/2018 A 15/06/2018
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'No se puede insertar una menstruacion en mitad de un embarazo'
		
		--INSERTAR UN CICLO MENSTRUAL CUYA FECHA DE INICIO INVADA LA FECHA DE FIN DEL EMBARAZO ANTERIOR 
			INSERT INTO CICLOMENSTRUAL (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180604','20180615')	--DEL 04/06/2018 A 15/06/2018
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'No se puede insertar una menstruacion en mitad de un embarazo'
		
		--INSERTAR UN CICLO MENSTRUAL CUYA DURACION INCLUYA EL PERIODO DEL EMBARAZO ANTERIOR
			INSERT INTO CICLOMENSTRUAL (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180604','20180615')	--DEL 01/05/2018 A 15/06/2018
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'No se puede insertar una menstruacion en mitad de un embarazo'

--PRUEBA QUE NO DEBE FALLAR:
--BORRAMOS LOS DATOS ANTERIORES
		--INSERTAR UN CICLO MENSTRUAL ANTES DEL EMBARAZO ANTERIOR
			INSERT INTO CICLOMENSTRUAL(ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180504','20180507')	--DEL 04/05/2018 A 07/05/2018
		--INSERTAR UN CICLO MENSTRUAL DESPUES DEL EMBARAZO ANTERIOR
			INSERT INTO CICLOMENSTRUAL(ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180704','20180707')	--DEL 04/07/2018 A 07/07/2018

			
			
						
			
			
			----------------------los mismos tests pero con la fecha de fin del ciclo primeramente insertado, a null ------------------




			--PRIMERO BORRAMOS TODOS LOS CICLOS DEL USUARIO DE PRUEBA
DELETE FROM EMBARAZO WHERE ID_USUARIO = 'USUARIOPRUEBA'
GO
DELETE FROM CICLOMENSTRUAL WHERE ID_USUARIO = 'USUARIOPRUEBA'

--COMPROBAMOS QUE ESTAN BORRADOS
SELECT * FROM CICLOMENSTRUAL WHERE ID_USUARIO = 'USUARIOPRUEBA'

GO
SELECT * FROM EMBARAZO WHERE ID_USUARIO = 'USUARIOPRUEBA'

--CREAMOS UN CICLO MENSTRUAL CON FECHA DE INICIO Y DE FIN 
INSERT INTO CICLOMENSTRUAL (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
VALUES('USUARIOPRUEBA', '20180601',null)	--EL CICLO DURA DEL 01/06/2018 AL sin fecha de cierre

--AHORA PRUEBAS QUE DEBEN FALLAR:
		--INSERTAR UN CICLO MENSTRUAL DENTRO DEL PERIODO DEL CICLO MENSTRUAL ANTERIOR
			INSERT INTO CICLOMENSTRUAL (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180602','20180604')	--DEL 02/06/2018 AL 04/06/2018
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'Ya existe un ciclo menstrual en esa fecha'

		--INSERTAR UN CICLO MENSTRUAL CUYA FECHA DE FIN INVADA LA FECHA DE INICIO DEL CICLO MENSTRUAL ANTERIOR
			INSERT INTO CICLOMENSTRUAL (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180602',NULL)	--DEL 02/06/2018 A SIN FECHA DE CIERRE
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'Ya existe un ciclo menstrual en esa fecha'

		--INSERTAR UN CICLO MENSTRUAL CUYA FECHA DE FIN INVADA LA FECHA DE INICIO DEL CICLO MENSTRUAL ANTERIOR Y LA FECHA DE FIN SOBREPASE LA
			--FECHA DE FIN DEL CICLO ANTERIOR
			INSERT INTO CICLOMENSTRUAL (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180602','20180615')	--DEL 02/06/2018 A 15/06/2018
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'Ya existe un ciclo menstrual en esa fecha'
		
		--INSERTAR UN CICLO MENSTRUAL CUYA FECHA DE INICIO INVADA LA FECHA DE FIN DEL CICLO MENSTRUAL ANTERIOR 
			INSERT INTO CICLOMENSTRUAL (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180604','20180615')	--DEL 04/06/2018 A 15/06/2018
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'Ya existe un ciclo menstrual en esa fecha'
		
		--INSERTAR UN CICLO MENSTRUAL CUYA DURACION INCLUYA EL PERIODO DEL CICLO ANTERIOR
			INSERT INTO CICLOMENSTRUAL (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180604','20180615')	--DEL 01/05/2018 A 15/06/2018
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'Ya existe un ciclo menstrual en esa fecha'


--PRUEBAS QUE DEBEN FALLAR ESTA VEZ AÑADIENDO UN EMBARAZO (EXISTIENDO YA UN CICLO MENSTRUAL)
--AHORA PRUEBAS QUE DEBEN FALLAR:
		--INSERTAR UN EMBARAZO DENTRO DEL PERIODO DEL CICLO MENSTRUAL ANTERIOR
			INSERT INTO EMBARAZO(ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180602','20180604')	--DEL 02/06/2018 AL 04/06/2018
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'No se puede insertar un embarazo en mitad de un ciclo'

		--INSERTAR UN EMBARAZO CUYA FECHA DE FIN INVADA LA FECHA DE INICIO DEL CICLO MENSTRUAL ANTERIOR
			INSERT INTO EMBARAZO (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180602',NULL)	--DEL 02/06/2018 A SIN FECHA DE CIERRE
				
				---EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'No se puede insertar un embarazo en mitad de un ciclo'

		--INSERTAR UN EMBARAZO CUYA FECHA DE FIN INVADA LA FECHA DE INICIO DEL CICLO MENSTRUAL ANTERIOR Y LA FECHA DE FIN SOBREPASE LA
			--FECHA DE FIN DEL CICLO ANTERIOR
			INSERT INTO EMBARAZO (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180602','20180615')	--DEL 02/06/2018 A 15/06/2018
				
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'No se puede insertar un embarazo en mitad de un ciclo'
		
		--INSERTAR UN EMBARAZO CUYA FECHA DE INICIO INVADA LA FECHA DE FIN DEL CICLO MENSTRUAL ANTERIOR 
			INSERT INTO EMBARAZO (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180604','20180615')	--DEL 04/06/2018 A 15/06/2018
				---EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'No se puede insertar un embarazo en mitad de un ciclo'
		
		--INSERTAR UN EMBARAZO CUYA DURACION INCLUYA EL PERIODO DEL CICLO ANTERIOR
			INSERT INTO EMBARAZO (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180604','20180615')	--DEL 01/05/2018 A 15/06/2018
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'No se puede insertar un embarazo en mitad de un ciclo'

				-----------------------------------------------------------------------------------------------




--AHORA VOLVEMOS A BORRAR TODO DEL USUARIO

--PRIMERO BORRAMOS TODOS LOS CICLOS DEL USUARIO DE PRUEBA
DELETE FROM EMBARAZO WHERE ID_USUARIO = 'USUARIOPRUEBA'
GO
DELETE FROM CICLOMENSTRUAL WHERE ID_USUARIO = 'USUARIOPRUEBA'

--COMPROBAMOS QUE ESTAN BORRADOS
SELECT * FROM CICLOMENSTRUAL WHERE ID_USUARIO = 'USUARIOPRUEBA'

GO
SELECT * FROM EMBARAZO WHERE ID_USUARIO = 'USUARIOPRUEBA'

--CREAMOS UN EMBARAZO CON FECHA DE INICIO Y DE FIN 
INSERT INTO EMBARAZO(ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
VALUES('USUARIOPRUEBA', '20180601', null)	--EL CICLO DURA DEL 01/06/2018 AL sin fecha de fin


--AHORA PRUEBAS QUE DEBEN FALLAR:
		--INSERTAR UN EMBARAZO DENTRO DEL PERIODO DEL CICLO EMBARAZO
			INSERT INTO EMBARAZO (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180602','20180604')	--DEL 02/06/2018 AL 04/06/2018
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'Ya existe un embarazo en esa fecha'

		--INSERTAR UN EMBARAZO CUYA FECHA DE FIN INVADA LA FECHA DE INICIO DEL EMBARAZO ANTERIOR
			INSERT INTO EMBARAZO (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180602',NULL)	--DEL 02/06/2018 A SIN FECHA DE CIERRE
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'Ya existe un embarazo en esa fecha'

		--INSERTAR UN EMBARAZO CUYA FECHA DE FIN INVADA LA FECHA DE INICIO DEL EMBARAZO ANTERIOR Y LA FECHA DE FIN SOBREPASE LA
			--FECHA DE FIN DEL EMBARAZO ANTERIOR
			INSERT INTO EMBARAZO (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180602','20180615')	--DEL 02/06/2018 A 15/06/2018
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'Ya existe un embarazo en esa fecha'
		
		--INSERTAR UN EMBARAZO CUYA FECHA DE INICIO INVADA LA FECHA DE FIN DEL EMBARAZO ANTERIOR 
			INSERT INTO EMBARAZO (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180604','20180615')	--DEL 04/06/2018 A 15/06/2018
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'Ya existe un embarazo en esa fecha'
		
		--INSERTAR UN EMBARAZOL CUYA DURACION INCLUYA EL PERIODO DEL EMBARAZO ANTERIOR
			INSERT INTO EMBARAZO (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180604','20180615')	--DEL 01/05/2018 A 15/06/2018
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'Ya existe un embarazo en esa fecha'


--PRUEBAS QUE DEBEN FALLAR ESTA VEZ AÑADIENDO UN CICLOMENSTRUAL (EXISTIENDO YA UN EMBARAZO)
--AHORA PRUEBAS QUE DEBEN FALLAR:
		--INSERTAR UN CICLO MENSTRUAL DENTRO DEL PERIODO DEL EMBARAZO ANTERIOR
			INSERT INTO CICLOMENSTRUAL(ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180602','20180604')	--DEL 02/06/2018 AL 04/06/2018
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'No se puede insertar una menstruacion en mitad de un embarazo'

		--INSERTAR UN CICLO MENSTRUAL CUYA FECHA DE FIN INVADA LA FECHA DE INICIO DEL EMBARAZO ANTERIOR
			INSERT INTO CICLOMENSTRUAL (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180602',NULL)	--DEL 02/06/2018 A SIN FECHA DE CIERRE
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'No se puede insertar una menstruacion en mitad de un embarazo'

		--INSERTAR UN CICLO MENSTRUAL CUYA FECHA DE FIN INVADA LA FECHA DE INICIO DEL EMBARAZO ANTERIOR Y LA FECHA DE FIN SOBREPASE LA
			--FECHA DE FIN DEL EMBARAZO ANTERIOR
			INSERT INTO CICLOMENSTRUAL (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180602','20180615')	--DEL 02/06/2018 A 15/06/2018
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'No se puede insertar una menstruacion en mitad de un embarazo'
		
		--INSERTAR UN CICLO MENSTRUAL CUYA FECHA DE INICIO INVADA LA FECHA DE FIN DEL EMBARAZO ANTERIOR 
			INSERT INTO CICLOMENSTRUAL (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180604','20180615')	--DEL 04/06/2018 A 15/06/2018
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'No se puede insertar una menstruacion en mitad de un embarazo'
		
		--INSERTAR UN CICLO MENSTRUAL CUYA DURACION INCLUYA EL PERIODO DEL EMBARAZO ANTERIOR
			INSERT INTO CICLOMENSTRUAL (ID_USUARIO, FECHAINICIO, FECHAFIN_REAL)
			VALUES('USUARIOPRUEBA', '20180604','20180615')	--DEL 01/05/2018 A 15/06/2018
				--EFECTIVAMENTE SALTA EL TRIGGER CON EL MENSAJE: 'No se puede insertar una menstruacion en mitad de un embarazo'

			
		