/*TRIGGER PARA CADA VEZ
QUE UNA USUARIA INSERTA EL PESO EN LA TABLA REVISION MEDICA,
SE ACTUALICE EL PESO DE LA TABLA USUARIO
*/
USE MenstruApp
BEGIN TRAN
ALTER
--CREATE
TRIGGER modificarPeso 
ON REVISIONMEDICA
AFTER INSERT AS
BEGIN
	UPDATE
		USUARIO
	SET
		USUARIO.PESO = REVISION.PESO
	FROM
		USUARIO AS USU
	INNER JOIN
		EMBARAZO AS EM
	ON USU.NICK = EM.ID_USUARIO
	INNER JOIN 
		REVISIONMEDICA AS REVISION
	ON EM.ID = REVISION.ID_EMBARAZO
END

