/*TRIGGER PARA CADA VEZ
QUE UNA USUARIA INSERTA EL PESO EN LA TABLA REVISION MEDICA,
SE ACTUALICE EL PESO DE LA TABLA USUARIO
*/
USE MenstruApp
BEGIN TRAN
ALTER
--CREATE
TRIGGER modificarPeso 
ON REVISIONMEDICA
AFTER INSERT AS
BEGIN
	UPDATE
		USUARIO
	SET
		USUARIO.PESO = REVISION.PESO
	FROM
		USUARIO AS USU
	INNER JOIN
		EMBARAZO AS EM
	ON USU.NICK = EM.ID_USUARIO
	INNER JOIN 
		(
		/*ASI COGE EL REGISTRO MAS NUEVO DEL PESO*/
		SELECT TOP 1 ID_EMBARAZO,PESO, FECHA_CITA_ACTUAL
		FROM REVISIONMEDICA
		ORDER BY FECHA_CITA_ACTUAL DESC
		) AS REVISION
	ON EM.ID = REVISION.ID_EMBARAZO 
END


SELECT * FROM USUARIO
SELECT * FROM EMBARAZO
SELECT * FROM REVISIONMEDICA

INSERT INTO REVISIONMEDICA (ID_EMBARAZO, PESO, CINTURA, CADERA, ESTADOFETO, OBSERVACIONES,FECHA_CITA_ACTUAL, FECHA_SIGUIENTE_CITA)
VALUES('CDBD8786-4033-43F3-B253-4A2F85EE6E64', 150,50,50, 'TODO BIEN', 'TODO PERFE TIA', '20200725','20200526')

INSERT INTO REVISIONMEDICA (ID_EMBARAZO, PESO, CINTURA, CADERA, ESTADOFETO, OBSERVACIONES, FECHA_CITA_ACTUAL,FECHA_SIGUIENTE_CITA)
VALUES('CDBD8786-4033-43F3-B253-4A2F85EE6E64', 70,50,50, 'TODO BIEN', 'TODO PERFE TIA', '20190626','20200526')

INSERT INTO REVISIONMEDICA (ID_EMBARAZO, PESO, CINTURA, CADERA, ESTADOFETO, OBSERVACIONES, FECHA_CITA_ACTUAL,FECHA_SIGUIENTE_CITA)
VALUES('CDBD8786-4033-43F3-B253-4A2F85EE6E64', 150,50,50, 'TODO BIEN', 'TODO PERFE TIA', '20190627','20200526')


ALTER
--CREATE
TRIGGER insertarNulosUsuario 
ON USUARIO
AFTER INSERT AS
BEGIN
/*SOLO VALE PARA CUANDO INSERTAS DE UNO EN UNO*/
/*solo es necesario hacer esto con el PESO porque es un tipo de
dato primitivo y por tanto no puedo ponerlo a nulo en java, sino a 0
entonces para que no se ponga a 0 en la bbdd sino a null, hago este trigger*/
	IF ((SELECT PESO FROM inserted) = 0)
	BEGIN
	UPDATE USUARIO
	SET PESO = NULL
	WHERE NICK = (SELECT NICK FROM inserted)
	END
END


/*trigger para que no se pueda insertar un embarazo
si ya hay uno en curso (sin fecha de fin)
*/

ALTER
--CREATE
TRIGGER noMasDeUnEmbarazoALaVez 
ON EMBARAZO
AFTER INSERT AS
BEGIN
	IF EXISTS (select  E.ID, E.ID_USUARIO, E.FECHAINICIO, E.FECHAFIN_REAL
					from EMBARAZO AS E
					INNER JOIN inserted AS I
					ON E.ID_USUARIO = I.ID_USUARIO
						AND E.ID != I.ID
					where E.FECHAFIN_REAL IS NULL 
				)
	BEGIN
		RAISERROR('Actualmente existe un embarazo en curso',16,1)
		ROLLBACK
	END
END

ALTER
--CREATE
TRIGGER noMasDeUnaMenstruacionALaVez 
ON CICLOMENSTRUAL
AFTER INSERT AS
BEGIN
	IF EXISTS (select  E.ID, E.ID_USUARIO, E.FECHAINICIO, E.FECHAFIN_REAL
					from CICLOMENSTRUAL AS E
					INNER JOIN inserted AS I
					ON E.ID_USUARIO = I.ID_USUARIO
					AND E.ID != I.ID
					where E.FECHAFIN_REAL IS NULL 
				)
	BEGIN
		RAISERROR('Actualmente existe un ciclo menstrual en curso',16,1)
		ROLLBACK
	END
END